-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_3x3_sobelConvolve is
port (
    ap_ready : OUT STD_LOGIC;
    window_adjust_0_0_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (79 downto 0) );
end;


architecture behav of conv2d_3x3_sobelConvolve is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal zext_ln38_3_fu_148_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_2_fu_140_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_160_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_166_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_1_fu_132_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_fu_124_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_fu_178_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_fu_184_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_0_load_cast_fu_156_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_1_fu_188_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_1_fu_174_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_4_fu_202_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_fu_206_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_3_fu_194_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_1_fu_212_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_8_fu_218_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_234_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_226_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_8_fu_256_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_fu_222_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_8_fu_306_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_7_fu_298_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp83_fu_318_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_324_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_6_fu_290_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_5_fu_282_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_2_fu_336_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_2_fu_342_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_1_load_cast_fu_314_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_3_fu_346_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_5_fu_332_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_9_fu_360_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_2_fu_364_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_7_fu_352_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_3_fu_370_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_fu_376_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_392_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_11_fu_384_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_1_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_1_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_1_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_9_fu_414_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_1_fu_380_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_13_fu_464_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_12_fu_456_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp86_fu_476_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_482_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_11_fu_448_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_10_fu_440_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_4_fu_494_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_4_fu_500_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_2_load_cast_fu_472_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_5_fu_504_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_9_fu_490_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_14_fu_518_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_4_fu_522_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_11_fu_510_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_5_fu_528_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_9_fu_534_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_550_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_13_fu_542_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_2_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_2_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_2_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_10_fu_572_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_2_fu_538_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_18_fu_622_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_17_fu_614_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp89_fu_634_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_640_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_16_fu_606_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_15_fu_598_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_6_fu_652_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_6_fu_658_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_3_load_cast_fu_630_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_7_fu_662_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_13_fu_648_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_19_fu_676_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_6_fu_680_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_15_fu_668_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_7_fu_686_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_10_fu_692_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_708_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_700_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_3_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_3_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_3_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_11_fu_730_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_3_fu_696_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_23_fu_780_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_22_fu_772_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp92_fu_792_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_798_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_21_fu_764_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_20_fu_756_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_8_fu_810_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_8_fu_816_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_4_load_cast_fu_788_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_9_fu_820_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_16_fu_806_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_24_fu_834_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_8_fu_838_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_17_fu_826_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_9_fu_844_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_11_fu_850_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_866_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_858_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_4_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_4_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_4_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_12_fu_888_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_4_fu_854_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_28_fu_938_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_27_fu_930_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp95_fu_950_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_956_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_26_fu_922_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_25_fu_914_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_10_fu_968_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_10_fu_974_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_5_load_cast_fu_946_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_11_fu_978_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_18_fu_964_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_29_fu_992_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_10_fu_996_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_19_fu_984_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_11_fu_1002_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_12_fu_1008_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_1024_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_fu_1016_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_5_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_5_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_5_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_13_fu_1046_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_5_fu_1012_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_33_fu_1096_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_32_fu_1088_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp98_fu_1108_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_1114_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_31_fu_1080_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_30_fu_1072_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_12_fu_1126_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_12_fu_1132_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_6_load_cast_fu_1104_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_13_fu_1136_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_20_fu_1122_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_34_fu_1150_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_12_fu_1154_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_21_fu_1142_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_13_fu_1160_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_13_fu_1166_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_fu_1182_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_fu_1174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_6_fu_1198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_6_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_6_fu_1212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_14_fu_1204_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_6_fu_1170_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_38_fu_1254_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_37_fu_1246_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp101_fu_1266_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_fu_1272_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_36_fu_1238_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_35_fu_1230_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln38_14_fu_1284_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln38_14_fu_1290_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_7_load_cast_fu_1262_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln38_15_fu_1294_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_22_fu_1280_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_39_fu_1308_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_14_fu_1312_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln38_23_fu_1300_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_15_fu_1318_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_14_fu_1324_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_1340_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_fu_1332_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_7_fu_1356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_7_fu_1350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln41_7_fu_1370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_15_fu_1362_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln41_7_fu_1328_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_fu_270_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_1_fu_428_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_2_fu_586_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_3_fu_744_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_4_fu_902_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_5_fu_1060_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_6_fu_1218_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln41_7_fu_1376_p3 : STD_LOGIC_VECTOR (9 downto 0);


begin



    add_ln38_10_fu_996_p2 <= std_logic_vector(signed(sext_ln38_18_fu_964_p1) + signed(zext_ln38_29_fu_992_p1));
    add_ln38_11_fu_1002_p2 <= std_logic_vector(unsigned(add_ln38_10_fu_996_p2) + unsigned(sext_ln38_19_fu_984_p1));
    add_ln38_12_fu_1154_p2 <= std_logic_vector(signed(sext_ln38_20_fu_1122_p1) + signed(zext_ln38_34_fu_1150_p1));
    add_ln38_13_fu_1160_p2 <= std_logic_vector(unsigned(add_ln38_12_fu_1154_p2) + unsigned(sext_ln38_21_fu_1142_p1));
    add_ln38_14_fu_1312_p2 <= std_logic_vector(signed(sext_ln38_22_fu_1280_p1) + signed(zext_ln38_39_fu_1308_p1));
    add_ln38_15_fu_1318_p2 <= std_logic_vector(unsigned(add_ln38_14_fu_1312_p2) + unsigned(sext_ln38_23_fu_1300_p1));
    add_ln38_1_fu_212_p2 <= std_logic_vector(unsigned(add_ln38_fu_206_p2) + unsigned(sext_ln38_3_fu_194_p1));
    add_ln38_2_fu_364_p2 <= std_logic_vector(signed(sext_ln38_5_fu_332_p1) + signed(zext_ln38_9_fu_360_p1));
    add_ln38_3_fu_370_p2 <= std_logic_vector(unsigned(add_ln38_2_fu_364_p2) + unsigned(sext_ln38_7_fu_352_p1));
    add_ln38_4_fu_522_p2 <= std_logic_vector(signed(sext_ln38_9_fu_490_p1) + signed(zext_ln38_14_fu_518_p1));
    add_ln38_5_fu_528_p2 <= std_logic_vector(unsigned(add_ln38_4_fu_522_p2) + unsigned(sext_ln38_11_fu_510_p1));
    add_ln38_6_fu_680_p2 <= std_logic_vector(signed(sext_ln38_13_fu_648_p1) + signed(zext_ln38_19_fu_676_p1));
    add_ln38_7_fu_686_p2 <= std_logic_vector(unsigned(add_ln38_6_fu_680_p2) + unsigned(sext_ln38_15_fu_668_p1));
    add_ln38_8_fu_838_p2 <= std_logic_vector(signed(sext_ln38_16_fu_806_p1) + signed(zext_ln38_24_fu_834_p1));
    add_ln38_9_fu_844_p2 <= std_logic_vector(unsigned(add_ln38_8_fu_838_p2) + unsigned(sext_ln38_17_fu_826_p1));
    add_ln38_fu_206_p2 <= std_logic_vector(signed(sext_ln38_1_fu_174_p1) + signed(zext_ln38_4_fu_202_p1));
    ap_ready <= ap_const_logic_1;
    ap_return <= (((((((select_ln41_fu_270_p3 & select_ln41_1_fu_428_p3) & select_ln41_2_fu_586_p3) & select_ln41_3_fu_744_p3) & select_ln41_4_fu_902_p3) & select_ln41_5_fu_1060_p3) & select_ln41_6_fu_1218_p3) & select_ln41_7_fu_1376_p3);
    icmp_ln43_1_fu_402_p2 <= "1" when (signed(tmp_12_fu_392_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_2_fu_560_p2 <= "1" when (signed(tmp_14_fu_550_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_3_fu_718_p2 <= "1" when (signed(tmp_16_fu_708_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_4_fu_876_p2 <= "1" when (signed(tmp_18_fu_866_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_5_fu_1034_p2 <= "1" when (signed(tmp_20_fu_1024_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_6_fu_1192_p2 <= "1" when (signed(tmp_22_fu_1182_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_7_fu_1350_p2 <= "1" when (signed(tmp_24_fu_1340_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln43_fu_244_p2 <= "1" when (signed(tmp_10_fu_234_p4) > signed(ap_const_lv3_0)) else "0";
    or_ln41_1_fu_422_p2 <= (tmp_11_fu_384_p3 or icmp_ln43_1_fu_402_p2);
    or_ln41_2_fu_580_p2 <= (tmp_13_fu_542_p3 or icmp_ln43_2_fu_560_p2);
    or_ln41_3_fu_738_p2 <= (tmp_15_fu_700_p3 or icmp_ln43_3_fu_718_p2);
    or_ln41_4_fu_896_p2 <= (tmp_17_fu_858_p3 or icmp_ln43_4_fu_876_p2);
    or_ln41_5_fu_1054_p2 <= (tmp_19_fu_1016_p3 or icmp_ln43_5_fu_1034_p2);
    or_ln41_6_fu_1212_p2 <= (tmp_21_fu_1174_p3 or icmp_ln43_6_fu_1192_p2);
    or_ln41_7_fu_1370_p2 <= (tmp_23_fu_1332_p3 or icmp_ln43_7_fu_1350_p2);
    or_ln41_fu_264_p2 <= (tmp_9_fu_226_p3 or icmp_ln43_fu_244_p2);
    select_ln41_10_fu_572_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_2_fu_566_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_11_fu_730_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_3_fu_724_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_12_fu_888_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_4_fu_882_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_13_fu_1046_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_5_fu_1040_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_14_fu_1204_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_6_fu_1198_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_15_fu_1362_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_7_fu_1356_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_1_fu_428_p3 <= 
        select_ln41_9_fu_414_p3 when (or_ln41_1_fu_422_p2(0) = '1') else 
        trunc_ln41_1_fu_380_p1;
    select_ln41_2_fu_586_p3 <= 
        select_ln41_10_fu_572_p3 when (or_ln41_2_fu_580_p2(0) = '1') else 
        trunc_ln41_2_fu_538_p1;
    select_ln41_3_fu_744_p3 <= 
        select_ln41_11_fu_730_p3 when (or_ln41_3_fu_738_p2(0) = '1') else 
        trunc_ln41_3_fu_696_p1;
    select_ln41_4_fu_902_p3 <= 
        select_ln41_12_fu_888_p3 when (or_ln41_4_fu_896_p2(0) = '1') else 
        trunc_ln41_4_fu_854_p1;
    select_ln41_5_fu_1060_p3 <= 
        select_ln41_13_fu_1046_p3 when (or_ln41_5_fu_1054_p2(0) = '1') else 
        trunc_ln41_5_fu_1012_p1;
    select_ln41_6_fu_1218_p3 <= 
        select_ln41_14_fu_1204_p3 when (or_ln41_6_fu_1212_p2(0) = '1') else 
        trunc_ln41_6_fu_1170_p1;
    select_ln41_7_fu_1376_p3 <= 
        select_ln41_15_fu_1362_p3 when (or_ln41_7_fu_1370_p2(0) = '1') else 
        trunc_ln41_7_fu_1328_p1;
    select_ln41_8_fu_256_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_fu_250_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_9_fu_414_p3 <= 
        ap_const_lv10_3FF when (xor_ln41_1_fu_408_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln41_fu_270_p3 <= 
        select_ln41_8_fu_256_p3 when (or_ln41_fu_264_p2(0) = '1') else 
        trunc_ln41_fu_222_p1;
        sext_ln38_10_fu_974_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_10_fu_968_p2),12));

        sext_ln38_11_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_5_fu_504_p2),13));

        sext_ln38_12_fu_1132_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_12_fu_1126_p2),12));

        sext_ln38_13_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_640_p3),13));

        sext_ln38_14_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_14_fu_1284_p2),12));

        sext_ln38_15_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_7_fu_662_p2),13));

        sext_ln38_16_fu_806_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_798_p3),13));

        sext_ln38_17_fu_826_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_9_fu_820_p2),13));

        sext_ln38_18_fu_964_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_956_p3),13));

        sext_ln38_19_fu_984_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_11_fu_978_p2),13));

        sext_ln38_1_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_166_p3),13));

        sext_ln38_20_fu_1122_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_1114_p3),13));

        sext_ln38_21_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_13_fu_1136_p2),13));

        sext_ln38_22_fu_1280_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_1272_p3),13));

        sext_ln38_23_fu_1300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_15_fu_1294_p2),13));

        sext_ln38_2_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_2_fu_336_p2),12));

        sext_ln38_3_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_1_fu_188_p2),13));

        sext_ln38_4_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_4_fu_494_p2),12));

        sext_ln38_5_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_324_p3),13));

        sext_ln38_6_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_6_fu_652_p2),12));

        sext_ln38_7_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_3_fu_346_p2),13));

        sext_ln38_8_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_8_fu_810_p2),12));

        sext_ln38_9_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_482_p3),13));

        sext_ln38_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_fu_178_p2),12));

        sext_ln41_10_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_7_fu_686_p2),32));

        sext_ln41_11_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_9_fu_844_p2),32));

        sext_ln41_12_fu_1008_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_11_fu_1002_p2),32));

        sext_ln41_13_fu_1166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_13_fu_1160_p2),32));

        sext_ln41_14_fu_1324_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_15_fu_1318_p2),32));

        sext_ln41_8_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_1_fu_212_p2),32));

        sext_ln41_9_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_5_fu_528_p2),32));

        sext_ln41_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_3_fu_370_p2),32));

    sub_ln38_10_fu_968_p2 <= std_logic_vector(unsigned(zext_ln38_26_fu_922_p1) - unsigned(zext_ln38_25_fu_914_p1));
    sub_ln38_11_fu_978_p2 <= std_logic_vector(signed(sext_ln38_10_fu_974_p1) - signed(window_adjust_2_0_5_load_cast_fu_946_p1));
    sub_ln38_12_fu_1126_p2 <= std_logic_vector(unsigned(zext_ln38_31_fu_1080_p1) - unsigned(zext_ln38_30_fu_1072_p1));
    sub_ln38_13_fu_1136_p2 <= std_logic_vector(signed(sext_ln38_12_fu_1132_p1) - signed(window_adjust_2_0_6_load_cast_fu_1104_p1));
    sub_ln38_14_fu_1284_p2 <= std_logic_vector(unsigned(zext_ln38_36_fu_1238_p1) - unsigned(zext_ln38_35_fu_1230_p1));
    sub_ln38_15_fu_1294_p2 <= std_logic_vector(signed(sext_ln38_14_fu_1290_p1) - signed(window_adjust_2_0_7_load_cast_fu_1262_p1));
    sub_ln38_1_fu_188_p2 <= std_logic_vector(signed(sext_ln38_fu_184_p1) - signed(window_adjust_2_0_0_load_cast_fu_156_p1));
    sub_ln38_2_fu_336_p2 <= std_logic_vector(unsigned(zext_ln38_6_fu_290_p1) - unsigned(zext_ln38_5_fu_282_p1));
    sub_ln38_3_fu_346_p2 <= std_logic_vector(signed(sext_ln38_2_fu_342_p1) - signed(window_adjust_2_0_1_load_cast_fu_314_p1));
    sub_ln38_4_fu_494_p2 <= std_logic_vector(unsigned(zext_ln38_11_fu_448_p1) - unsigned(zext_ln38_10_fu_440_p1));
    sub_ln38_5_fu_504_p2 <= std_logic_vector(signed(sext_ln38_4_fu_500_p1) - signed(window_adjust_2_0_2_load_cast_fu_472_p1));
    sub_ln38_6_fu_652_p2 <= std_logic_vector(unsigned(zext_ln38_16_fu_606_p1) - unsigned(zext_ln38_15_fu_598_p1));
    sub_ln38_7_fu_662_p2 <= std_logic_vector(signed(sext_ln38_6_fu_658_p1) - signed(window_adjust_2_0_3_load_cast_fu_630_p1));
    sub_ln38_8_fu_810_p2 <= std_logic_vector(unsigned(zext_ln38_21_fu_764_p1) - unsigned(zext_ln38_20_fu_756_p1));
    sub_ln38_9_fu_820_p2 <= std_logic_vector(signed(sext_ln38_8_fu_816_p1) - signed(window_adjust_2_0_4_load_cast_fu_788_p1));
    sub_ln38_fu_178_p2 <= std_logic_vector(unsigned(zext_ln38_1_fu_132_p1) - unsigned(zext_ln38_fu_124_p1));
    tmp101_fu_1266_p2 <= std_logic_vector(unsigned(zext_ln38_38_fu_1254_p1) - unsigned(zext_ln38_37_fu_1246_p1));
    tmp83_fu_318_p2 <= std_logic_vector(unsigned(zext_ln38_8_fu_306_p1) - unsigned(zext_ln38_7_fu_298_p1));
    tmp86_fu_476_p2 <= std_logic_vector(unsigned(zext_ln38_13_fu_464_p1) - unsigned(zext_ln38_12_fu_456_p1));
    tmp89_fu_634_p2 <= std_logic_vector(unsigned(zext_ln38_18_fu_622_p1) - unsigned(zext_ln38_17_fu_614_p1));
    tmp92_fu_792_p2 <= std_logic_vector(unsigned(zext_ln38_23_fu_780_p1) - unsigned(zext_ln38_22_fu_772_p1));
    tmp95_fu_950_p2 <= std_logic_vector(unsigned(zext_ln38_28_fu_938_p1) - unsigned(zext_ln38_27_fu_930_p1));
    tmp98_fu_1108_p2 <= std_logic_vector(unsigned(zext_ln38_33_fu_1096_p1) - unsigned(zext_ln38_32_fu_1088_p1));
    tmp_10_fu_234_p4 <= add_ln38_1_fu_212_p2(12 downto 10);
    tmp_11_fu_384_p3 <= sext_ln41_fu_376_p1(31 downto 31);
    tmp_12_fu_392_p4 <= add_ln38_3_fu_370_p2(12 downto 10);
    tmp_13_fu_542_p3 <= sext_ln41_9_fu_534_p1(31 downto 31);
    tmp_14_fu_550_p4 <= add_ln38_5_fu_528_p2(12 downto 10);
    tmp_15_fu_700_p3 <= sext_ln41_10_fu_692_p1(31 downto 31);
    tmp_16_fu_708_p4 <= add_ln38_7_fu_686_p2(12 downto 10);
    tmp_17_fu_858_p3 <= sext_ln41_11_fu_850_p1(31 downto 31);
    tmp_18_fu_866_p4 <= add_ln38_9_fu_844_p2(12 downto 10);
    tmp_19_fu_1016_p3 <= sext_ln41_12_fu_1008_p1(31 downto 31);
    tmp_1_fu_166_p3 <= (tmp_fu_160_p2 & ap_const_lv1_0);
    tmp_20_fu_1024_p4 <= add_ln38_11_fu_1002_p2(12 downto 10);
    tmp_21_fu_1174_p3 <= sext_ln41_13_fu_1166_p1(31 downto 31);
    tmp_22_fu_1182_p4 <= add_ln38_13_fu_1160_p2(12 downto 10);
    tmp_23_fu_1332_p3 <= sext_ln41_14_fu_1324_p1(31 downto 31);
    tmp_24_fu_1340_p4 <= add_ln38_15_fu_1318_p2(12 downto 10);
    tmp_2_fu_324_p3 <= (tmp83_fu_318_p2 & ap_const_lv1_0);
    tmp_3_fu_482_p3 <= (tmp86_fu_476_p2 & ap_const_lv1_0);
    tmp_4_fu_640_p3 <= (tmp89_fu_634_p2 & ap_const_lv1_0);
    tmp_5_fu_798_p3 <= (tmp92_fu_792_p2 & ap_const_lv1_0);
    tmp_6_fu_956_p3 <= (tmp95_fu_950_p2 & ap_const_lv1_0);
    tmp_7_fu_1114_p3 <= (tmp98_fu_1108_p2 & ap_const_lv1_0);
    tmp_8_fu_1272_p3 <= (tmp101_fu_1266_p2 & ap_const_lv1_0);
    tmp_9_fu_226_p3 <= sext_ln41_8_fu_218_p1(31 downto 31);
    tmp_fu_160_p2 <= std_logic_vector(unsigned(zext_ln38_3_fu_148_p1) - unsigned(zext_ln38_2_fu_140_p1));
    trunc_ln41_1_fu_380_p1 <= add_ln38_3_fu_370_p2(10 - 1 downto 0);
    trunc_ln41_2_fu_538_p1 <= add_ln38_5_fu_528_p2(10 - 1 downto 0);
    trunc_ln41_3_fu_696_p1 <= add_ln38_7_fu_686_p2(10 - 1 downto 0);
    trunc_ln41_4_fu_854_p1 <= add_ln38_9_fu_844_p2(10 - 1 downto 0);
    trunc_ln41_5_fu_1012_p1 <= add_ln38_11_fu_1002_p2(10 - 1 downto 0);
    trunc_ln41_6_fu_1170_p1 <= add_ln38_13_fu_1160_p2(10 - 1 downto 0);
    trunc_ln41_7_fu_1328_p1 <= add_ln38_15_fu_1318_p2(10 - 1 downto 0);
    trunc_ln41_fu_222_p1 <= add_ln38_1_fu_212_p2(10 - 1 downto 0);
    window_adjust_2_0_0_load_cast_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_0),12));
    window_adjust_2_0_1_load_cast_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_1),12));
    window_adjust_2_0_2_load_cast_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_2),12));
    window_adjust_2_0_3_load_cast_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_3),12));
    window_adjust_2_0_4_load_cast_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_4),12));
    window_adjust_2_0_5_load_cast_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_5),12));
    window_adjust_2_0_6_load_cast_fu_1104_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_6),12));
    window_adjust_2_0_7_load_cast_fu_1262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_7),12));
    xor_ln41_1_fu_408_p2 <= (tmp_11_fu_384_p3 xor ap_const_lv1_1);
    xor_ln41_2_fu_566_p2 <= (tmp_13_fu_542_p3 xor ap_const_lv1_1);
    xor_ln41_3_fu_724_p2 <= (tmp_15_fu_700_p3 xor ap_const_lv1_1);
    xor_ln41_4_fu_882_p2 <= (tmp_17_fu_858_p3 xor ap_const_lv1_1);
    xor_ln41_5_fu_1040_p2 <= (tmp_19_fu_1016_p3 xor ap_const_lv1_1);
    xor_ln41_6_fu_1198_p2 <= (tmp_21_fu_1174_p3 xor ap_const_lv1_1);
    xor_ln41_7_fu_1356_p2 <= (tmp_23_fu_1332_p3 xor ap_const_lv1_1);
    xor_ln41_fu_250_p2 <= (tmp_9_fu_226_p3 xor ap_const_lv1_1);
    zext_ln38_10_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_2),11));
    zext_ln38_11_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_2),11));
    zext_ln38_12_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_2),11));
    zext_ln38_13_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_2),11));
    zext_ln38_14_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_2),13));
    zext_ln38_15_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_3),11));
    zext_ln38_16_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_3),11));
    zext_ln38_17_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_3),11));
    zext_ln38_18_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_3),11));
    zext_ln38_19_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_3),13));
    zext_ln38_1_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_0),11));
    zext_ln38_20_fu_756_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_4),11));
    zext_ln38_21_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_4),11));
    zext_ln38_22_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_4),11));
    zext_ln38_23_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_4),11));
    zext_ln38_24_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_4),13));
    zext_ln38_25_fu_914_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_5),11));
    zext_ln38_26_fu_922_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_5),11));
    zext_ln38_27_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_5),11));
    zext_ln38_28_fu_938_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_5),11));
    zext_ln38_29_fu_992_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_5),13));
    zext_ln38_2_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_0),11));
    zext_ln38_30_fu_1072_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_6),11));
    zext_ln38_31_fu_1080_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_6),11));
    zext_ln38_32_fu_1088_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_6),11));
    zext_ln38_33_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_6),11));
    zext_ln38_34_fu_1150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_6),13));
    zext_ln38_35_fu_1230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_7),11));
    zext_ln38_36_fu_1238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_7),11));
    zext_ln38_37_fu_1246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_7),11));
    zext_ln38_38_fu_1254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_7),11));
    zext_ln38_39_fu_1308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_7),13));
    zext_ln38_3_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_0),11));
    zext_ln38_4_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_0),13));
    zext_ln38_5_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_1),11));
    zext_ln38_6_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_1),11));
    zext_ln38_7_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_1),11));
    zext_ln38_8_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_1),11));
    zext_ln38_9_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_1),13));
    zext_ln38_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_0),11));
end behav;
