-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_3x3_conv2d_3x3_Pipeline_VITIS_LOOP_157_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_r_dout : IN STD_LOGIC_VECTOR (79 downto 0);
    output_r_empty_n : IN STD_LOGIC;
    output_r_read : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    arr2 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of conv2d_3x3_conv2d_3x3_Pipeline_VITIS_LOOP_157_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv20_99000 : STD_LOGIC_VECTOR (19 downto 0) := "10011001000000000000";
    constant ap_const_lv32_BF400 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000010111111010000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv20_4 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000100";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal icmp_ln157_reg_649 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal icmp_ln167_2_reg_693 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op102_write_state5 : BOOLEAN;
    signal icmp_ln167_3_reg_713 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op105_writereq_state5 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal icmp_ln157_reg_649_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_2_reg_693_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op140_writeresp_state10 : BOOLEAN;
    signal ap_block_state10_pp0_stage4_iter1 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage4 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal output_addr : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal gmem_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal gmem_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem_blk_n_B : STD_LOGIC;
    signal icmp_ln167_3_reg_713_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal icmp_ln167_1_reg_673 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_1_reg_673_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln167_reg_653 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_reg_653_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_4_reg_733 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_4_reg_733_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal output_r_blk_n : STD_LOGIC;
    signal ap_predicate_op121_write_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_predicate_op143_writeresp_state11 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_predicate_op56_write_state3 : BOOLEAN;
    signal ap_predicate_op59_writereq_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_predicate_op131_writeresp_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal reg_234 : STD_LOGIC_VECTOR (79 downto 0);
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_predicate_op41_writereq_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_state12_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_predicate_op77_write_state4 : BOOLEAN;
    signal ap_predicate_op80_writereq_state4 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_predicate_op136_writeresp_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal reg_244 : STD_LOGIC_VECTOR (79 downto 0);
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal icmp_ln157_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln169_fu_268_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln4_reg_662 : STD_LOGIC_VECTOR (60 downto 0);
    signal icmp_ln167_1_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln169_2_fu_335_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln169_1_reg_682 : STD_LOGIC_VECTOR (60 downto 0);
    signal icmp_ln167_2_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln169_4_fu_395_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln169_2_reg_702 : STD_LOGIC_VECTOR (60 downto 0);
    signal icmp_ln167_3_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln169_6_fu_473_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln169_3_reg_722 : STD_LOGIC_VECTOR (60 downto 0);
    signal icmp_ln167_4_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln169_4_reg_737 : STD_LOGIC_VECTOR (60 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_empty_31_reg_188 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_30_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_29_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_reg_215 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln169_1_fu_319_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln169_3_fu_379_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln169_5_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln169_7_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln169_9_fu_613_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln169_fu_374_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal tmp_76_fu_448_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal tmp_77_fu_526_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage4_01001 : BOOLEAN;
    signal tmp_78_fu_604_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal add_ln169_8_fu_551_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_92 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal i_2_fu_308_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln_fu_280_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln169_fu_288_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln169_1_fu_292_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln169_1_fu_347_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln169_2_fu_355_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln169_3_fu_359_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln169_2_fu_407_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln169_4_fu_415_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln169_5_fu_419_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln169_5_fu_444_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_17_fu_434_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln169_3_fu_485_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln169_6_fu_493_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln169_7_fu_497_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln169_6_fu_522_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_512_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln169_4_fu_563_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln169_8_fu_571_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln169_9_fu_575_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln169_7_fu_600_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_21_fu_590_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage1 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_596 : BOOLEAN;
    signal ap_condition_595 : BOOLEAN;
    signal ap_condition_593 : BOOLEAN;
    signal ap_condition_598 : BOOLEAN;
    signal ap_condition_842 : BOOLEAN;
    signal ap_condition_846 : BOOLEAN;
    signal ap_condition_850 : BOOLEAN;
    signal ap_condition_854 : BOOLEAN;
    signal ap_condition_858 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_3x3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv2d_3x3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage4,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage4)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_empty_29_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_596)) then
                if ((icmp_ln167_2_fu_389_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_empty_29_reg_206 <= add_ln169_4_fu_395_p2;
                elsif ((icmp_ln167_2_fu_389_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_empty_29_reg_206 <= output_addr;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_empty_30_reg_197_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_595)) then
                if ((icmp_ln167_1_fu_329_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_empty_30_reg_197 <= add_ln169_2_fu_335_p2;
                elsif ((icmp_ln167_1_fu_329_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_empty_30_reg_197 <= output_addr;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_empty_31_reg_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_593)) then
                if ((icmp_ln167_fu_262_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_empty_31_reg_188 <= output_addr;
                elsif ((icmp_ln167_fu_262_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_empty_31_reg_188 <= add_ln169_fu_268_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_empty_reg_215_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_598)) then
                if ((icmp_ln167_3_fu_467_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_empty_reg_215 <= add_ln169_6_fu_473_p2;
                elsif ((icmp_ln167_3_fu_467_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_empty_reg_215 <= output_addr;
                end if;
            end if; 
        end if;
    end process;

    i_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln157_fu_256_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_92 <= i_2_fu_308_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_92 <= ap_const_lv20_0;
                end if;
            end if; 
        end if;
    end process;

    output_addr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_858)) then 
                    output_addr <= add_ln169_fu_268_p2;
                elsif ((ap_const_boolean_1 = ap_condition_854)) then 
                    output_addr <= add_ln169_2_fu_335_p2;
                elsif ((ap_const_boolean_1 = ap_condition_850)) then 
                    output_addr <= add_ln169_4_fu_395_p2;
                elsif ((ap_const_boolean_1 = ap_condition_846)) then 
                    output_addr <= add_ln169_6_fu_473_p2;
                elsif ((ap_const_boolean_1 = ap_condition_842)) then 
                    output_addr <= add_ln169_8_fu_551_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln157_reg_649 <= icmp_ln157_fu_256_p2;
                icmp_ln157_reg_649_pp0_iter1_reg <= icmp_ln157_reg_649;
                icmp_ln167_reg_653 <= icmp_ln167_fu_262_p2;
                icmp_ln167_reg_653_pp0_iter1_reg <= icmp_ln167_reg_653;
                trunc_ln4_reg_662 <= add_ln169_1_fu_292_p2(63 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                icmp_ln167_1_reg_673 <= icmp_ln167_1_fu_329_p2;
                icmp_ln167_1_reg_673_pp0_iter1_reg <= icmp_ln167_1_reg_673;
                trunc_ln169_1_reg_682 <= add_ln169_3_fu_359_p2(63 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                icmp_ln167_2_reg_693 <= icmp_ln167_2_fu_389_p2;
                icmp_ln167_2_reg_693_pp0_iter1_reg <= icmp_ln167_2_reg_693;
                trunc_ln169_2_reg_702 <= add_ln169_5_fu_419_p2(63 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                icmp_ln167_3_reg_713 <= icmp_ln167_3_fu_467_p2;
                icmp_ln167_3_reg_713_pp0_iter1_reg <= icmp_ln167_3_reg_713;
                trunc_ln169_3_reg_722 <= add_ln169_7_fu_497_p2(63 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001))) then
                icmp_ln167_4_reg_733 <= icmp_ln167_4_fu_545_p2;
                icmp_ln167_4_reg_733_pp0_iter1_reg <= icmp_ln167_4_reg_733;
                trunc_ln169_4_reg_737 <= add_ln169_9_fu_575_p2(63 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)))) then
                reg_234 <= output_r_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)))) then
                reg_244 <= output_r_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage4_subdone, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter1_stage1, ap_idle_pp0_0to0, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to2, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln169_1_fu_292_p2 <= std_logic_vector(signed(sext_ln169_fu_288_p1) + signed(arr2));
    add_ln169_2_fu_335_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_empty_31_reg_188) + unsigned(ap_const_lv32_1));
    add_ln169_3_fu_359_p2 <= std_logic_vector(signed(sext_ln169_2_fu_355_p1) + signed(arr2));
    add_ln169_4_fu_395_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_empty_30_reg_197) + unsigned(ap_const_lv32_1));
    add_ln169_5_fu_419_p2 <= std_logic_vector(signed(sext_ln169_4_fu_415_p1) + signed(arr2));
    add_ln169_6_fu_473_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_empty_29_reg_206) + unsigned(ap_const_lv32_1));
    add_ln169_7_fu_497_p2 <= std_logic_vector(signed(sext_ln169_6_fu_493_p1) + signed(arr2));
    add_ln169_8_fu_551_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_empty_reg_215) + unsigned(ap_const_lv32_1));
    add_ln169_9_fu_575_p2 <= std_logic_vector(signed(sext_ln169_8_fu_571_p1) + signed(arr2));
    add_ln169_fu_268_p2 <= std_logic_vector(unsigned(output_addr) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state11_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_io, ap_block_state11_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_io, ap_block_state11_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage1_iter0, ap_block_state12_pp0_stage1_iter2)
    begin
                ap_block_pp0_stage1_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage1_iter2)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0)));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage1_iter0, ap_block_state2_io, ap_block_state7_io, ap_block_state12_pp0_stage1_iter2)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage1_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0))));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage1_iter0, ap_block_state2_io, ap_block_state7_io, ap_block_state12_pp0_stage1_iter2)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage1_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0))));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage2_iter0, ap_block_state8_pp0_stage2_iter1)
    begin
                ap_block_pp0_stage2_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0)));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage2_iter0, ap_block_state3_io, ap_block_state8_pp0_stage2_iter1)
    begin
                ap_block_pp0_stage2_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0))));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage2_iter0, ap_block_state3_io, ap_block_state8_pp0_stage2_iter1)
    begin
                ap_block_pp0_stage2_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0))));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage3_iter0, ap_block_state9_pp0_stage3_iter1)
    begin
                ap_block_pp0_stage3_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage3_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0)));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage3_iter0, ap_block_state4_io, ap_block_state9_pp0_stage3_iter1)
    begin
                ap_block_pp0_stage3_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage3_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0))));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage3_iter0, ap_block_state4_io, ap_block_state9_pp0_stage3_iter1)
    begin
                ap_block_pp0_stage3_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage3_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0))));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state5_pp0_stage4_iter0, ap_block_state10_pp0_stage4_iter1)
    begin
                ap_block_pp0_stage4_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage4_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0)));
    end process;


    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state5_pp0_stage4_iter0, ap_block_state5_io, ap_block_state10_pp0_stage4_iter1)
    begin
                ap_block_pp0_stage4_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage4_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0))));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state5_pp0_stage4_iter0, ap_block_state5_io, ap_block_state10_pp0_stage4_iter1)
    begin
                ap_block_pp0_stage4_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage4_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0))));
    end process;


    ap_block_state10_pp0_stage4_iter1_assign_proc : process(m_axi_gmem_BVALID, ap_predicate_op140_writeresp_state10)
    begin
                ap_block_state10_pp0_stage4_iter1 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (ap_predicate_op140_writeresp_state10 = ap_const_boolean_1));
    end process;


    ap_block_state11_pp0_stage0_iter2_assign_proc : process(m_axi_gmem_BVALID, ap_predicate_op143_writeresp_state11)
    begin
                ap_block_state11_pp0_stage0_iter2 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (ap_predicate_op143_writeresp_state11 = ap_const_boolean_1));
    end process;


    ap_block_state12_pp0_stage1_iter2_assign_proc : process(m_axi_gmem_BVALID, icmp_ln167_4_reg_733_pp0_iter1_reg)
    begin
                ap_block_state12_pp0_stage1_iter2 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (icmp_ln167_4_reg_733_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_block_state2_io_assign_proc : process(m_axi_gmem_AWREADY, ap_predicate_op41_writereq_state2)
    begin
                ap_block_state2_io <= ((m_axi_gmem_AWREADY = ap_const_logic_0) and (ap_predicate_op41_writereq_state2 = ap_const_boolean_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(output_r_empty_n, icmp_ln157_reg_649)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(m_axi_gmem_AWREADY, m_axi_gmem_WREADY, ap_predicate_op56_write_state3, ap_predicate_op59_writereq_state3)
    begin
                ap_block_state3_io <= (((m_axi_gmem_AWREADY = ap_const_logic_0) and (ap_predicate_op59_writereq_state3 = ap_const_boolean_1)) or ((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_predicate_op56_write_state3 = ap_const_boolean_1)));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(output_r_empty_n, icmp_ln157_reg_649)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem_AWREADY, m_axi_gmem_WREADY, ap_predicate_op77_write_state4, ap_predicate_op80_writereq_state4)
    begin
                ap_block_state4_io <= (((m_axi_gmem_AWREADY = ap_const_logic_0) and (ap_predicate_op80_writereq_state4 = ap_const_boolean_1)) or ((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_predicate_op77_write_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(output_r_empty_n, icmp_ln157_reg_649)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_io_assign_proc : process(m_axi_gmem_AWREADY, m_axi_gmem_WREADY, ap_predicate_op102_write_state5, ap_predicate_op105_writereq_state5)
    begin
                ap_block_state5_io <= (((m_axi_gmem_AWREADY = ap_const_logic_0) and (ap_predicate_op105_writereq_state5 = ap_const_boolean_1)) or ((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1)));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(output_r_empty_n, icmp_ln157_reg_649)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0));
    end process;


    ap_block_state6_io_assign_proc : process(m_axi_gmem_AWREADY, m_axi_gmem_WREADY, icmp_ln167_4_reg_733, ap_predicate_op121_write_state6)
    begin
                ap_block_state6_io <= (((m_axi_gmem_AWREADY = ap_const_logic_0) and (icmp_ln167_4_reg_733 = ap_const_lv1_1)) or ((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_predicate_op121_write_state6 = ap_const_boolean_1)));
    end process;


    ap_block_state7_io_assign_proc : process(m_axi_gmem_WREADY, icmp_ln167_4_reg_733)
    begin
                ap_block_state7_io <= ((m_axi_gmem_WREADY = ap_const_logic_0) and (icmp_ln167_4_reg_733 = ap_const_lv1_1));
    end process;


    ap_block_state8_pp0_stage2_iter1_assign_proc : process(m_axi_gmem_BVALID, ap_predicate_op131_writeresp_state8)
    begin
                ap_block_state8_pp0_stage2_iter1 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (ap_predicate_op131_writeresp_state8 = ap_const_boolean_1));
    end process;


    ap_block_state9_pp0_stage3_iter1_assign_proc : process(m_axi_gmem_BVALID, ap_predicate_op136_writeresp_state9)
    begin
                ap_block_state9_pp0_stage3_iter1 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (ap_predicate_op136_writeresp_state9 = ap_const_boolean_1));
    end process;


    ap_condition_593_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln157_fu_256_p2)
    begin
                ap_condition_593 <= ((icmp_ln157_fu_256_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_595_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln157_reg_649, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
                ap_condition_595 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001));
    end process;


    ap_condition_596_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln157_reg_649, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
                ap_condition_596 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001));
    end process;


    ap_condition_598_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln157_reg_649, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_598 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001));
    end process;


    ap_condition_842_assign_proc : process(ap_CS_fsm_pp0_stage4, icmp_ln157_reg_649, ap_block_pp0_stage4_11001, icmp_ln167_4_fu_545_p2)
    begin
                ap_condition_842 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_4_fu_545_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001));
    end process;


    ap_condition_846_assign_proc : process(icmp_ln157_reg_649, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, icmp_ln167_3_fu_467_p2)
    begin
                ap_condition_846 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_3_fu_467_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001));
    end process;


    ap_condition_850_assign_proc : process(icmp_ln157_reg_649, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, icmp_ln167_2_fu_389_p2)
    begin
                ap_condition_850 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_2_fu_389_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001));
    end process;


    ap_condition_854_assign_proc : process(icmp_ln157_reg_649, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln167_1_fu_329_p2)
    begin
                ap_condition_854 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_1_fu_329_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001));
    end process;


    ap_condition_858_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln157_fu_256_p2, icmp_ln167_fu_262_p2)
    begin
                ap_condition_858 <= ((icmp_ln167_fu_262_p2 = ap_const_lv1_1) and (icmp_ln157_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_exit_pp0_iter0_stage4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, icmp_ln157_reg_649, ap_block_pp0_stage4_subdone)
    begin
        if (((icmp_ln157_reg_649 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone))) then 
            ap_condition_exit_pp0_iter0_stage4 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage1_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln157_reg_649_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_condition_exit_pp0_iter1_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage4;

    ap_predicate_op102_write_state5_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_2_reg_693)
    begin
                ap_predicate_op102_write_state5 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_2_reg_693 = ap_const_lv1_1));
    end process;


    ap_predicate_op105_writereq_state5_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_3_reg_713)
    begin
                ap_predicate_op105_writereq_state5 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_3_reg_713 = ap_const_lv1_1));
    end process;


    ap_predicate_op121_write_state6_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_3_reg_713)
    begin
                ap_predicate_op121_write_state6 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_3_reg_713 = ap_const_lv1_1));
    end process;


    ap_predicate_op131_writeresp_state8_assign_proc : process(icmp_ln157_reg_649_pp0_iter1_reg, icmp_ln167_reg_653_pp0_iter1_reg)
    begin
                ap_predicate_op131_writeresp_state8 <= ((icmp_ln167_reg_653_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op136_writeresp_state9_assign_proc : process(icmp_ln157_reg_649_pp0_iter1_reg, icmp_ln167_1_reg_673_pp0_iter1_reg)
    begin
                ap_predicate_op136_writeresp_state9 <= ((icmp_ln167_1_reg_673_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op140_writeresp_state10_assign_proc : process(icmp_ln157_reg_649_pp0_iter1_reg, icmp_ln167_2_reg_693_pp0_iter1_reg)
    begin
                ap_predicate_op140_writeresp_state10 <= ((icmp_ln167_2_reg_693_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op143_writeresp_state11_assign_proc : process(icmp_ln157_reg_649_pp0_iter1_reg, icmp_ln167_3_reg_713_pp0_iter1_reg)
    begin
                ap_predicate_op143_writeresp_state11 <= ((icmp_ln167_3_reg_713_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op41_writereq_state2_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_reg_653)
    begin
                ap_predicate_op41_writereq_state2 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_reg_653 = ap_const_lv1_1));
    end process;


    ap_predicate_op56_write_state3_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_reg_653)
    begin
                ap_predicate_op56_write_state3 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_reg_653 = ap_const_lv1_1));
    end process;


    ap_predicate_op59_writereq_state3_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_1_reg_673)
    begin
                ap_predicate_op59_writereq_state3 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_1_reg_673 = ap_const_lv1_1));
    end process;


    ap_predicate_op77_write_state4_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_1_reg_673)
    begin
                ap_predicate_op77_write_state4 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_1_reg_673 = ap_const_lv1_1));
    end process;


    ap_predicate_op80_writereq_state4_assign_proc : process(icmp_ln157_reg_649, icmp_ln167_2_reg_693)
    begin
                ap_predicate_op80_writereq_state4 <= ((icmp_ln157_reg_649 = ap_const_lv1_1) and (icmp_ln167_2_reg_693 = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_92, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv20_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_92;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, icmp_ln157_reg_649, m_axi_gmem_AWREADY, icmp_ln167_2_reg_693, ap_predicate_op105_writereq_state5, ap_block_pp0_stage4, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, icmp_ln167_1_reg_673, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, icmp_ln167_reg_653, icmp_ln167_4_reg_733)
    begin
        if ((((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln167_reg_653 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln167_1_reg_673 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln167_2_reg_693 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_4_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_predicate_op105_writereq_state5 
    = ap_const_boolean_1)))) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage4, m_axi_gmem_BVALID, icmp_ln157_reg_649_pp0_iter1_reg, ap_predicate_op140_writeresp_state10, ap_block_pp0_stage4, ap_block_pp0_stage0, icmp_ln167_3_reg_713_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, icmp_ln167_1_reg_673_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, icmp_ln167_reg_653_pp0_iter1_reg, icmp_ln167_4_reg_733_pp0_iter1_reg)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln167_4_reg_733_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln167_3_reg_713_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_predicate_op140_writeresp_state10 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_reg_653_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_1_reg_673_pp0_iter1_reg = ap_const_lv1_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln157_reg_649_pp0_iter1_reg = ap_const_lv1_1)))) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, icmp_ln157_reg_649, m_axi_gmem_WREADY, ap_predicate_op102_write_state5, icmp_ln167_3_reg_713, ap_block_pp0_stage4, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, icmp_ln167_1_reg_673, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, icmp_ln167_reg_653, icmp_ln167_4_reg_733)
    begin
        if ((((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln167_3_reg_713 = ap_const_lv1_1)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln167_reg_653 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln167_1_reg_673 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_4_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_predicate_op102_write_state5 
    = ap_const_boolean_1)))) then 
            gmem_blk_n_W <= m_axi_gmem_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    i_2_fu_308_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv20_4));
    icmp_ln157_fu_256_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) < unsigned(ap_const_lv20_99000)) else "0";
    icmp_ln167_1_fu_329_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_empty_31_reg_188) < signed(ap_const_lv32_BF400)) else "0";
    icmp_ln167_2_fu_389_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_empty_30_reg_197) < signed(ap_const_lv32_BF400)) else "0";
    icmp_ln167_3_fu_467_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_empty_29_reg_206) < signed(ap_const_lv32_BF400)) else "0";
    icmp_ln167_4_fu_545_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_empty_reg_215) < signed(ap_const_lv32_BF400)) else "0";
    icmp_ln167_fu_262_p2 <= "1" when (signed(output_addr) < signed(ap_const_lv32_BF400)) else "0";
    m_axi_gmem_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_ARVALID <= ap_const_logic_0;

    m_axi_gmem_AWADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_predicate_op105_writereq_state5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, icmp_ln167_4_reg_733, ap_block_pp0_stage0_11001, ap_predicate_op59_writereq_state3, ap_block_pp0_stage2_11001, ap_predicate_op41_writereq_state2, ap_block_pp0_stage1_11001, ap_predicate_op80_writereq_state4, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, sext_ln169_1_fu_319_p1, sext_ln169_3_fu_379_p1, sext_ln169_5_fu_457_p1, sext_ln169_7_fu_535_p1, sext_ln169_9_fu_613_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_4_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_AWADDR <= sext_ln169_9_fu_613_p1;
        elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_predicate_op105_writereq_state5 = ap_const_boolean_1))) then 
            m_axi_gmem_AWADDR <= sext_ln169_7_fu_535_p1;
        elsif (((ap_predicate_op80_writereq_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
            m_axi_gmem_AWADDR <= sext_ln169_5_fu_457_p1;
        elsif (((ap_predicate_op59_writereq_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
            m_axi_gmem_AWADDR <= sext_ln169_3_fu_379_p1;
        elsif (((ap_predicate_op41_writereq_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            m_axi_gmem_AWADDR <= sext_ln169_1_fu_319_p1;
        else 
            m_axi_gmem_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_1;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;

    m_axi_gmem_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_predicate_op105_writereq_state5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, icmp_ln167_4_reg_733, ap_block_pp0_stage0_11001, ap_predicate_op59_writereq_state3, ap_block_pp0_stage2_11001, ap_predicate_op41_writereq_state2, ap_block_pp0_stage1_11001, ap_predicate_op80_writereq_state4, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_predicate_op80_writereq_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) or ((ap_predicate_op41_writereq_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_predicate_op59_writereq_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_4_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_predicate_op105_writereq_state5 = ap_const_boolean_1)))) then 
            m_axi_gmem_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_BREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage4, ap_predicate_op140_writeresp_state10, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, icmp_ln167_4_reg_733_pp0_iter1_reg, ap_predicate_op143_writeresp_state11, ap_block_pp0_stage0_11001, ap_predicate_op131_writeresp_state8, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001, ap_predicate_op136_writeresp_state9, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_predicate_op136_writeresp_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) or ((ap_predicate_op131_writeresp_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op143_writeresp_state11 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln167_4_reg_733_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_predicate_op140_writeresp_state10 
    = ap_const_boolean_1)))) then 
            m_axi_gmem_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_RREADY <= ap_const_logic_0;

    m_axi_gmem_WDATA_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_predicate_op102_write_state5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, icmp_ln167_4_reg_733, ap_predicate_op121_write_state6, ap_predicate_op56_write_state3, ap_predicate_op77_write_state4, reg_244, trunc_ln169_fu_374_p1, ap_block_pp0_stage2_01001, tmp_76_fu_448_p3, ap_block_pp0_stage3_01001, tmp_77_fu_526_p3, ap_block_pp0_stage4_01001, tmp_78_fu_604_p3, ap_block_pp0_stage0_01001, ap_block_pp0_stage1_01001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_4_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001))) then 
            m_axi_gmem_WDATA <= reg_244(79 downto 16);
        elsif (((ap_predicate_op121_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            m_axi_gmem_WDATA <= tmp_78_fu_604_p3;
        elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_01001) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) then 
            m_axi_gmem_WDATA <= tmp_77_fu_526_p3;
        elsif (((ap_predicate_op77_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001))) then 
            m_axi_gmem_WDATA <= tmp_76_fu_448_p3;
        elsif (((ap_predicate_op56_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001))) then 
            m_axi_gmem_WDATA <= trunc_ln169_fu_374_p1;
        else 
            m_axi_gmem_WDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv8_FF;
    m_axi_gmem_WUSER <= ap_const_lv1_0;

    m_axi_gmem_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_predicate_op102_write_state5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, icmp_ln167_4_reg_733, ap_predicate_op121_write_state6, ap_block_pp0_stage0_11001, ap_predicate_op56_write_state3, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001, ap_predicate_op77_write_state4, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_predicate_op77_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) or ((ap_predicate_op56_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_predicate_op121_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln167_4_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_predicate_op102_write_state5 = ap_const_boolean_1)))) then 
            m_axi_gmem_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    output_r_blk_n_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, output_r_empty_n, icmp_ln157_reg_649, ap_block_pp0_stage4, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1)
    begin
        if ((((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3)))) then 
            output_r_blk_n <= output_r_empty_n;
        else 
            output_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_r_read_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, icmp_ln157_reg_649, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((icmp_ln157_reg_649 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)))) then 
            output_r_read <= ap_const_logic_1;
        else 
            output_r_read <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln169_1_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln4_reg_662),64));

        sext_ln169_2_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln169_1_fu_347_p3),64));

        sext_ln169_3_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln169_1_reg_682),64));

        sext_ln169_4_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln169_2_fu_407_p3),64));

        sext_ln169_5_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln169_2_reg_702),64));

        sext_ln169_6_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln169_3_fu_485_p3),64));

        sext_ln169_7_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln169_3_reg_722),64));

        sext_ln169_8_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln169_4_fu_563_p3),64));

        sext_ln169_9_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln169_4_reg_737),64));

        sext_ln169_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_280_p3),64));

    shl_ln169_1_fu_347_p3 <= (ap_phi_reg_pp0_iter0_empty_31_reg_188 & ap_const_lv3_0);
    shl_ln169_2_fu_407_p3 <= (ap_phi_reg_pp0_iter0_empty_30_reg_197 & ap_const_lv3_0);
    shl_ln169_3_fu_485_p3 <= (ap_phi_reg_pp0_iter0_empty_29_reg_206 & ap_const_lv3_0);
    shl_ln169_4_fu_563_p3 <= (ap_phi_reg_pp0_iter0_empty_reg_215 & ap_const_lv3_0);
    shl_ln_fu_280_p3 <= (output_addr & ap_const_lv3_0);
    tmp_17_fu_434_p4 <= reg_234(79 downto 64);
    tmp_19_fu_512_p4 <= reg_244(79 downto 48);
    tmp_21_fu_590_p4 <= reg_234(79 downto 32);
    tmp_76_fu_448_p3 <= (trunc_ln169_5_fu_444_p1 & tmp_17_fu_434_p4);
    tmp_77_fu_526_p3 <= (trunc_ln169_6_fu_522_p1 & tmp_19_fu_512_p4);
    tmp_78_fu_604_p3 <= (trunc_ln169_7_fu_600_p1 & tmp_21_fu_590_p4);
    trunc_ln169_5_fu_444_p1 <= reg_244(48 - 1 downto 0);
    trunc_ln169_6_fu_522_p1 <= reg_234(32 - 1 downto 0);
    trunc_ln169_7_fu_600_p1 <= reg_244(16 - 1 downto 0);
    trunc_ln169_fu_374_p1 <= reg_234(64 - 1 downto 0);
end behav;
