// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_sobelConvolve (
        ap_ready,
        window_adjust_0_0_0,
        window_adjust_0_2_0,
        window_adjust_1_0_0,
        window_adjust_1_2_0,
        window_adjust_2_0_0,
        window_adjust_2_2_0,
        window_adjust_0_0_1,
        window_adjust_0_2_1,
        window_adjust_1_0_1,
        window_adjust_1_2_1,
        window_adjust_2_0_1,
        window_adjust_2_2_1,
        window_adjust_0_0_2,
        window_adjust_0_2_2,
        window_adjust_1_0_2,
        window_adjust_1_2_2,
        window_adjust_2_0_2,
        window_adjust_2_2_2,
        window_adjust_0_0_3,
        window_adjust_0_2_3,
        window_adjust_1_0_3,
        window_adjust_1_2_3,
        window_adjust_2_0_3,
        window_adjust_2_2_3,
        window_adjust_0_0_4,
        window_adjust_0_2_4,
        window_adjust_1_0_4,
        window_adjust_1_2_4,
        window_adjust_2_0_4,
        window_adjust_2_2_4,
        window_adjust_0_0_5,
        window_adjust_0_2_5,
        window_adjust_1_0_5,
        window_adjust_1_2_5,
        window_adjust_2_0_5,
        window_adjust_2_2_5,
        window_adjust_0_0_6,
        window_adjust_0_2_6,
        window_adjust_1_0_6,
        window_adjust_1_2_6,
        window_adjust_2_0_6,
        window_adjust_2_2_6,
        window_adjust_0_0_7,
        window_adjust_0_2_7,
        window_adjust_1_0_7,
        window_adjust_1_2_7,
        window_adjust_2_0_7,
        window_adjust_2_2_7,
        ap_return
);


output   ap_ready;
input  [9:0] window_adjust_0_0_0;
input  [9:0] window_adjust_0_2_0;
input  [9:0] window_adjust_1_0_0;
input  [9:0] window_adjust_1_2_0;
input  [9:0] window_adjust_2_0_0;
input  [9:0] window_adjust_2_2_0;
input  [9:0] window_adjust_0_0_1;
input  [9:0] window_adjust_0_2_1;
input  [9:0] window_adjust_1_0_1;
input  [9:0] window_adjust_1_2_1;
input  [9:0] window_adjust_2_0_1;
input  [9:0] window_adjust_2_2_1;
input  [9:0] window_adjust_0_0_2;
input  [9:0] window_adjust_0_2_2;
input  [9:0] window_adjust_1_0_2;
input  [9:0] window_adjust_1_2_2;
input  [9:0] window_adjust_2_0_2;
input  [9:0] window_adjust_2_2_2;
input  [9:0] window_adjust_0_0_3;
input  [9:0] window_adjust_0_2_3;
input  [9:0] window_adjust_1_0_3;
input  [9:0] window_adjust_1_2_3;
input  [9:0] window_adjust_2_0_3;
input  [9:0] window_adjust_2_2_3;
input  [9:0] window_adjust_0_0_4;
input  [9:0] window_adjust_0_2_4;
input  [9:0] window_adjust_1_0_4;
input  [9:0] window_adjust_1_2_4;
input  [9:0] window_adjust_2_0_4;
input  [9:0] window_adjust_2_2_4;
input  [9:0] window_adjust_0_0_5;
input  [9:0] window_adjust_0_2_5;
input  [9:0] window_adjust_1_0_5;
input  [9:0] window_adjust_1_2_5;
input  [9:0] window_adjust_2_0_5;
input  [9:0] window_adjust_2_2_5;
input  [9:0] window_adjust_0_0_6;
input  [9:0] window_adjust_0_2_6;
input  [9:0] window_adjust_1_0_6;
input  [9:0] window_adjust_1_2_6;
input  [9:0] window_adjust_2_0_6;
input  [9:0] window_adjust_2_2_6;
input  [9:0] window_adjust_0_0_7;
input  [9:0] window_adjust_0_2_7;
input  [9:0] window_adjust_1_0_7;
input  [9:0] window_adjust_1_2_7;
input  [9:0] window_adjust_2_0_7;
input  [9:0] window_adjust_2_2_7;
output  [79:0] ap_return;

wire   [10:0] zext_ln39_3_fu_148_p1;
wire   [10:0] zext_ln39_2_fu_140_p1;
wire   [10:0] tmp_fu_160_p2;
wire   [11:0] tmp_1_fu_166_p3;
wire   [10:0] zext_ln39_1_fu_132_p1;
wire   [10:0] zext_ln39_fu_124_p1;
wire   [10:0] sub_ln39_fu_178_p2;
wire  signed [11:0] sext_ln39_fu_184_p1;
wire   [11:0] window_adjust_2_0_0_load_cast_fu_156_p1;
wire   [11:0] sub_ln39_1_fu_188_p2;
wire  signed [12:0] sext_ln39_1_fu_174_p1;
wire   [12:0] zext_ln39_4_fu_202_p1;
wire   [12:0] add_ln39_fu_206_p2;
wire  signed [12:0] sext_ln39_3_fu_194_p1;
wire  signed [12:0] add_ln39_1_fu_212_p2;
wire  signed [31:0] sext_ln42_8_fu_218_p1;
wire   [2:0] tmp_10_fu_234_p4;
wire   [0:0] tmp_9_fu_226_p3;
wire   [0:0] xor_ln42_fu_250_p2;
wire   [0:0] icmp_ln44_fu_244_p2;
wire   [0:0] or_ln42_fu_264_p2;
wire   [9:0] select_ln42_8_fu_256_p3;
wire   [9:0] trunc_ln42_fu_222_p1;
wire   [10:0] zext_ln39_8_fu_306_p1;
wire   [10:0] zext_ln39_7_fu_298_p1;
wire   [10:0] tmp83_fu_318_p2;
wire   [11:0] tmp_2_fu_324_p3;
wire   [10:0] zext_ln39_6_fu_290_p1;
wire   [10:0] zext_ln39_5_fu_282_p1;
wire   [10:0] sub_ln39_2_fu_336_p2;
wire  signed [11:0] sext_ln39_2_fu_342_p1;
wire   [11:0] window_adjust_2_0_1_load_cast_fu_314_p1;
wire   [11:0] sub_ln39_3_fu_346_p2;
wire  signed [12:0] sext_ln39_5_fu_332_p1;
wire   [12:0] zext_ln39_9_fu_360_p1;
wire   [12:0] add_ln39_2_fu_364_p2;
wire  signed [12:0] sext_ln39_7_fu_352_p1;
wire  signed [12:0] add_ln39_3_fu_370_p2;
wire  signed [31:0] sext_ln42_fu_376_p1;
wire   [2:0] tmp_12_fu_392_p4;
wire   [0:0] tmp_11_fu_384_p3;
wire   [0:0] xor_ln42_1_fu_408_p2;
wire   [0:0] icmp_ln44_1_fu_402_p2;
wire   [0:0] or_ln42_1_fu_422_p2;
wire   [9:0] select_ln42_9_fu_414_p3;
wire   [9:0] trunc_ln42_1_fu_380_p1;
wire   [10:0] zext_ln39_13_fu_464_p1;
wire   [10:0] zext_ln39_12_fu_456_p1;
wire   [10:0] tmp86_fu_476_p2;
wire   [11:0] tmp_3_fu_482_p3;
wire   [10:0] zext_ln39_11_fu_448_p1;
wire   [10:0] zext_ln39_10_fu_440_p1;
wire   [10:0] sub_ln39_4_fu_494_p2;
wire  signed [11:0] sext_ln39_4_fu_500_p1;
wire   [11:0] window_adjust_2_0_2_load_cast_fu_472_p1;
wire   [11:0] sub_ln39_5_fu_504_p2;
wire  signed [12:0] sext_ln39_9_fu_490_p1;
wire   [12:0] zext_ln39_14_fu_518_p1;
wire   [12:0] add_ln39_4_fu_522_p2;
wire  signed [12:0] sext_ln39_11_fu_510_p1;
wire  signed [12:0] add_ln39_5_fu_528_p2;
wire  signed [31:0] sext_ln42_9_fu_534_p1;
wire   [2:0] tmp_14_fu_550_p4;
wire   [0:0] tmp_13_fu_542_p3;
wire   [0:0] xor_ln42_2_fu_566_p2;
wire   [0:0] icmp_ln44_2_fu_560_p2;
wire   [0:0] or_ln42_2_fu_580_p2;
wire   [9:0] select_ln42_10_fu_572_p3;
wire   [9:0] trunc_ln42_2_fu_538_p1;
wire   [10:0] zext_ln39_18_fu_622_p1;
wire   [10:0] zext_ln39_17_fu_614_p1;
wire   [10:0] tmp89_fu_634_p2;
wire   [11:0] tmp_4_fu_640_p3;
wire   [10:0] zext_ln39_16_fu_606_p1;
wire   [10:0] zext_ln39_15_fu_598_p1;
wire   [10:0] sub_ln39_6_fu_652_p2;
wire  signed [11:0] sext_ln39_6_fu_658_p1;
wire   [11:0] window_adjust_2_0_3_load_cast_fu_630_p1;
wire   [11:0] sub_ln39_7_fu_662_p2;
wire  signed [12:0] sext_ln39_13_fu_648_p1;
wire   [12:0] zext_ln39_19_fu_676_p1;
wire   [12:0] add_ln39_6_fu_680_p2;
wire  signed [12:0] sext_ln39_15_fu_668_p1;
wire  signed [12:0] add_ln39_7_fu_686_p2;
wire  signed [31:0] sext_ln42_10_fu_692_p1;
wire   [2:0] tmp_16_fu_708_p4;
wire   [0:0] tmp_15_fu_700_p3;
wire   [0:0] xor_ln42_3_fu_724_p2;
wire   [0:0] icmp_ln44_3_fu_718_p2;
wire   [0:0] or_ln42_3_fu_738_p2;
wire   [9:0] select_ln42_11_fu_730_p3;
wire   [9:0] trunc_ln42_3_fu_696_p1;
wire   [10:0] zext_ln39_23_fu_780_p1;
wire   [10:0] zext_ln39_22_fu_772_p1;
wire   [10:0] tmp92_fu_792_p2;
wire   [11:0] tmp_5_fu_798_p3;
wire   [10:0] zext_ln39_21_fu_764_p1;
wire   [10:0] zext_ln39_20_fu_756_p1;
wire   [10:0] sub_ln39_8_fu_810_p2;
wire  signed [11:0] sext_ln39_8_fu_816_p1;
wire   [11:0] window_adjust_2_0_4_load_cast_fu_788_p1;
wire   [11:0] sub_ln39_9_fu_820_p2;
wire  signed [12:0] sext_ln39_16_fu_806_p1;
wire   [12:0] zext_ln39_24_fu_834_p1;
wire   [12:0] add_ln39_8_fu_838_p2;
wire  signed [12:0] sext_ln39_17_fu_826_p1;
wire  signed [12:0] add_ln39_9_fu_844_p2;
wire  signed [31:0] sext_ln42_11_fu_850_p1;
wire   [2:0] tmp_18_fu_866_p4;
wire   [0:0] tmp_17_fu_858_p3;
wire   [0:0] xor_ln42_4_fu_882_p2;
wire   [0:0] icmp_ln44_4_fu_876_p2;
wire   [0:0] or_ln42_4_fu_896_p2;
wire   [9:0] select_ln42_12_fu_888_p3;
wire   [9:0] trunc_ln42_4_fu_854_p1;
wire   [10:0] zext_ln39_28_fu_938_p1;
wire   [10:0] zext_ln39_27_fu_930_p1;
wire   [10:0] tmp95_fu_950_p2;
wire   [11:0] tmp_6_fu_956_p3;
wire   [10:0] zext_ln39_26_fu_922_p1;
wire   [10:0] zext_ln39_25_fu_914_p1;
wire   [10:0] sub_ln39_10_fu_968_p2;
wire  signed [11:0] sext_ln39_10_fu_974_p1;
wire   [11:0] window_adjust_2_0_5_load_cast_fu_946_p1;
wire   [11:0] sub_ln39_11_fu_978_p2;
wire  signed [12:0] sext_ln39_18_fu_964_p1;
wire   [12:0] zext_ln39_29_fu_992_p1;
wire   [12:0] add_ln39_10_fu_996_p2;
wire  signed [12:0] sext_ln39_19_fu_984_p1;
wire  signed [12:0] add_ln39_11_fu_1002_p2;
wire  signed [31:0] sext_ln42_12_fu_1008_p1;
wire   [2:0] tmp_20_fu_1024_p4;
wire   [0:0] tmp_19_fu_1016_p3;
wire   [0:0] xor_ln42_5_fu_1040_p2;
wire   [0:0] icmp_ln44_5_fu_1034_p2;
wire   [0:0] or_ln42_5_fu_1054_p2;
wire   [9:0] select_ln42_13_fu_1046_p3;
wire   [9:0] trunc_ln42_5_fu_1012_p1;
wire   [10:0] zext_ln39_33_fu_1096_p1;
wire   [10:0] zext_ln39_32_fu_1088_p1;
wire   [10:0] tmp98_fu_1108_p2;
wire   [11:0] tmp_7_fu_1114_p3;
wire   [10:0] zext_ln39_31_fu_1080_p1;
wire   [10:0] zext_ln39_30_fu_1072_p1;
wire   [10:0] sub_ln39_12_fu_1126_p2;
wire  signed [11:0] sext_ln39_12_fu_1132_p1;
wire   [11:0] window_adjust_2_0_6_load_cast_fu_1104_p1;
wire   [11:0] sub_ln39_13_fu_1136_p2;
wire  signed [12:0] sext_ln39_20_fu_1122_p1;
wire   [12:0] zext_ln39_34_fu_1150_p1;
wire   [12:0] add_ln39_12_fu_1154_p2;
wire  signed [12:0] sext_ln39_21_fu_1142_p1;
wire  signed [12:0] add_ln39_13_fu_1160_p2;
wire  signed [31:0] sext_ln42_13_fu_1166_p1;
wire   [2:0] tmp_22_fu_1182_p4;
wire   [0:0] tmp_21_fu_1174_p3;
wire   [0:0] xor_ln42_6_fu_1198_p2;
wire   [0:0] icmp_ln44_6_fu_1192_p2;
wire   [0:0] or_ln42_6_fu_1212_p2;
wire   [9:0] select_ln42_14_fu_1204_p3;
wire   [9:0] trunc_ln42_6_fu_1170_p1;
wire   [10:0] zext_ln39_38_fu_1254_p1;
wire   [10:0] zext_ln39_37_fu_1246_p1;
wire   [10:0] tmp101_fu_1266_p2;
wire   [11:0] tmp_8_fu_1272_p3;
wire   [10:0] zext_ln39_36_fu_1238_p1;
wire   [10:0] zext_ln39_35_fu_1230_p1;
wire   [10:0] sub_ln39_14_fu_1284_p2;
wire  signed [11:0] sext_ln39_14_fu_1290_p1;
wire   [11:0] window_adjust_2_0_7_load_cast_fu_1262_p1;
wire   [11:0] sub_ln39_15_fu_1294_p2;
wire  signed [12:0] sext_ln39_22_fu_1280_p1;
wire   [12:0] zext_ln39_39_fu_1308_p1;
wire   [12:0] add_ln39_14_fu_1312_p2;
wire  signed [12:0] sext_ln39_23_fu_1300_p1;
wire  signed [12:0] add_ln39_15_fu_1318_p2;
wire  signed [31:0] sext_ln42_14_fu_1324_p1;
wire   [2:0] tmp_24_fu_1340_p4;
wire   [0:0] tmp_23_fu_1332_p3;
wire   [0:0] xor_ln42_7_fu_1356_p2;
wire   [0:0] icmp_ln44_7_fu_1350_p2;
wire   [0:0] or_ln42_7_fu_1370_p2;
wire   [9:0] select_ln42_15_fu_1362_p3;
wire   [9:0] trunc_ln42_7_fu_1328_p1;
wire   [9:0] select_ln42_fu_270_p3;
wire   [9:0] select_ln42_1_fu_428_p3;
wire   [9:0] select_ln42_2_fu_586_p3;
wire   [9:0] select_ln42_3_fu_744_p3;
wire   [9:0] select_ln42_4_fu_902_p3;
wire   [9:0] select_ln42_5_fu_1060_p3;
wire   [9:0] select_ln42_6_fu_1218_p3;
wire   [9:0] select_ln42_7_fu_1376_p3;

assign add_ln39_10_fu_996_p2 = ($signed(sext_ln39_18_fu_964_p1) + $signed(zext_ln39_29_fu_992_p1));

assign add_ln39_11_fu_1002_p2 = ($signed(add_ln39_10_fu_996_p2) + $signed(sext_ln39_19_fu_984_p1));

assign add_ln39_12_fu_1154_p2 = ($signed(sext_ln39_20_fu_1122_p1) + $signed(zext_ln39_34_fu_1150_p1));

assign add_ln39_13_fu_1160_p2 = ($signed(add_ln39_12_fu_1154_p2) + $signed(sext_ln39_21_fu_1142_p1));

assign add_ln39_14_fu_1312_p2 = ($signed(sext_ln39_22_fu_1280_p1) + $signed(zext_ln39_39_fu_1308_p1));

assign add_ln39_15_fu_1318_p2 = ($signed(add_ln39_14_fu_1312_p2) + $signed(sext_ln39_23_fu_1300_p1));

assign add_ln39_1_fu_212_p2 = ($signed(add_ln39_fu_206_p2) + $signed(sext_ln39_3_fu_194_p1));

assign add_ln39_2_fu_364_p2 = ($signed(sext_ln39_5_fu_332_p1) + $signed(zext_ln39_9_fu_360_p1));

assign add_ln39_3_fu_370_p2 = ($signed(add_ln39_2_fu_364_p2) + $signed(sext_ln39_7_fu_352_p1));

assign add_ln39_4_fu_522_p2 = ($signed(sext_ln39_9_fu_490_p1) + $signed(zext_ln39_14_fu_518_p1));

assign add_ln39_5_fu_528_p2 = ($signed(add_ln39_4_fu_522_p2) + $signed(sext_ln39_11_fu_510_p1));

assign add_ln39_6_fu_680_p2 = ($signed(sext_ln39_13_fu_648_p1) + $signed(zext_ln39_19_fu_676_p1));

assign add_ln39_7_fu_686_p2 = ($signed(add_ln39_6_fu_680_p2) + $signed(sext_ln39_15_fu_668_p1));

assign add_ln39_8_fu_838_p2 = ($signed(sext_ln39_16_fu_806_p1) + $signed(zext_ln39_24_fu_834_p1));

assign add_ln39_9_fu_844_p2 = ($signed(add_ln39_8_fu_838_p2) + $signed(sext_ln39_17_fu_826_p1));

assign add_ln39_fu_206_p2 = ($signed(sext_ln39_1_fu_174_p1) + $signed(zext_ln39_4_fu_202_p1));

assign ap_ready = 1'b1;

assign or_ln42_1_fu_422_p2 = (tmp_11_fu_384_p3 | icmp_ln44_1_fu_402_p2);

assign or_ln42_2_fu_580_p2 = (tmp_13_fu_542_p3 | icmp_ln44_2_fu_560_p2);

assign or_ln42_3_fu_738_p2 = (tmp_15_fu_700_p3 | icmp_ln44_3_fu_718_p2);

assign or_ln42_4_fu_896_p2 = (tmp_17_fu_858_p3 | icmp_ln44_4_fu_876_p2);

assign or_ln42_5_fu_1054_p2 = (tmp_19_fu_1016_p3 | icmp_ln44_5_fu_1034_p2);

assign or_ln42_6_fu_1212_p2 = (tmp_21_fu_1174_p3 | icmp_ln44_6_fu_1192_p2);

assign or_ln42_7_fu_1370_p2 = (tmp_23_fu_1332_p3 | icmp_ln44_7_fu_1350_p2);

assign or_ln42_fu_264_p2 = (tmp_9_fu_226_p3 | icmp_ln44_fu_244_p2);

assign select_ln42_10_fu_572_p3 = ((xor_ln42_2_fu_566_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_11_fu_730_p3 = ((xor_ln42_3_fu_724_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_12_fu_888_p3 = ((xor_ln42_4_fu_882_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_13_fu_1046_p3 = ((xor_ln42_5_fu_1040_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_14_fu_1204_p3 = ((xor_ln42_6_fu_1198_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_15_fu_1362_p3 = ((xor_ln42_7_fu_1356_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_1_fu_428_p3 = ((or_ln42_1_fu_422_p2[0:0] == 1'b1) ? select_ln42_9_fu_414_p3 : trunc_ln42_1_fu_380_p1);

assign select_ln42_2_fu_586_p3 = ((or_ln42_2_fu_580_p2[0:0] == 1'b1) ? select_ln42_10_fu_572_p3 : trunc_ln42_2_fu_538_p1);

assign select_ln42_3_fu_744_p3 = ((or_ln42_3_fu_738_p2[0:0] == 1'b1) ? select_ln42_11_fu_730_p3 : trunc_ln42_3_fu_696_p1);

assign select_ln42_4_fu_902_p3 = ((or_ln42_4_fu_896_p2[0:0] == 1'b1) ? select_ln42_12_fu_888_p3 : trunc_ln42_4_fu_854_p1);

assign select_ln42_5_fu_1060_p3 = ((or_ln42_5_fu_1054_p2[0:0] == 1'b1) ? select_ln42_13_fu_1046_p3 : trunc_ln42_5_fu_1012_p1);

assign select_ln42_6_fu_1218_p3 = ((or_ln42_6_fu_1212_p2[0:0] == 1'b1) ? select_ln42_14_fu_1204_p3 : trunc_ln42_6_fu_1170_p1);

assign select_ln42_7_fu_1376_p3 = ((or_ln42_7_fu_1370_p2[0:0] == 1'b1) ? select_ln42_15_fu_1362_p3 : trunc_ln42_7_fu_1328_p1);

assign select_ln42_8_fu_256_p3 = ((xor_ln42_fu_250_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_9_fu_414_p3 = ((xor_ln42_1_fu_408_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln42_fu_270_p3 = ((or_ln42_fu_264_p2[0:0] == 1'b1) ? select_ln42_8_fu_256_p3 : trunc_ln42_fu_222_p1);

assign sext_ln39_10_fu_974_p1 = $signed(sub_ln39_10_fu_968_p2);

assign sext_ln39_11_fu_510_p1 = $signed(sub_ln39_5_fu_504_p2);

assign sext_ln39_12_fu_1132_p1 = $signed(sub_ln39_12_fu_1126_p2);

assign sext_ln39_13_fu_648_p1 = $signed(tmp_4_fu_640_p3);

assign sext_ln39_14_fu_1290_p1 = $signed(sub_ln39_14_fu_1284_p2);

assign sext_ln39_15_fu_668_p1 = $signed(sub_ln39_7_fu_662_p2);

assign sext_ln39_16_fu_806_p1 = $signed(tmp_5_fu_798_p3);

assign sext_ln39_17_fu_826_p1 = $signed(sub_ln39_9_fu_820_p2);

assign sext_ln39_18_fu_964_p1 = $signed(tmp_6_fu_956_p3);

assign sext_ln39_19_fu_984_p1 = $signed(sub_ln39_11_fu_978_p2);

assign sext_ln39_1_fu_174_p1 = $signed(tmp_1_fu_166_p3);

assign sext_ln39_20_fu_1122_p1 = $signed(tmp_7_fu_1114_p3);

assign sext_ln39_21_fu_1142_p1 = $signed(sub_ln39_13_fu_1136_p2);

assign sext_ln39_22_fu_1280_p1 = $signed(tmp_8_fu_1272_p3);

assign sext_ln39_23_fu_1300_p1 = $signed(sub_ln39_15_fu_1294_p2);

assign sext_ln39_2_fu_342_p1 = $signed(sub_ln39_2_fu_336_p2);

assign sext_ln39_3_fu_194_p1 = $signed(sub_ln39_1_fu_188_p2);

assign sext_ln39_4_fu_500_p1 = $signed(sub_ln39_4_fu_494_p2);

assign sext_ln39_5_fu_332_p1 = $signed(tmp_2_fu_324_p3);

assign sext_ln39_6_fu_658_p1 = $signed(sub_ln39_6_fu_652_p2);

assign sext_ln39_7_fu_352_p1 = $signed(sub_ln39_3_fu_346_p2);

assign sext_ln39_8_fu_816_p1 = $signed(sub_ln39_8_fu_810_p2);

assign sext_ln39_9_fu_490_p1 = $signed(tmp_3_fu_482_p3);

assign sext_ln39_fu_184_p1 = $signed(sub_ln39_fu_178_p2);

assign sext_ln42_10_fu_692_p1 = add_ln39_7_fu_686_p2;

assign sext_ln42_11_fu_850_p1 = add_ln39_9_fu_844_p2;

assign sext_ln42_12_fu_1008_p1 = add_ln39_11_fu_1002_p2;

assign sext_ln42_13_fu_1166_p1 = add_ln39_13_fu_1160_p2;

assign sext_ln42_14_fu_1324_p1 = add_ln39_15_fu_1318_p2;

assign sext_ln42_8_fu_218_p1 = add_ln39_1_fu_212_p2;

assign sext_ln42_9_fu_534_p1 = add_ln39_5_fu_528_p2;

assign sext_ln42_fu_376_p1 = add_ln39_3_fu_370_p2;

assign sub_ln39_10_fu_968_p2 = (zext_ln39_26_fu_922_p1 - zext_ln39_25_fu_914_p1);

assign sub_ln39_11_fu_978_p2 = ($signed(sext_ln39_10_fu_974_p1) - $signed(window_adjust_2_0_5_load_cast_fu_946_p1));

assign sub_ln39_12_fu_1126_p2 = (zext_ln39_31_fu_1080_p1 - zext_ln39_30_fu_1072_p1);

assign sub_ln39_13_fu_1136_p2 = ($signed(sext_ln39_12_fu_1132_p1) - $signed(window_adjust_2_0_6_load_cast_fu_1104_p1));

assign sub_ln39_14_fu_1284_p2 = (zext_ln39_36_fu_1238_p1 - zext_ln39_35_fu_1230_p1);

assign sub_ln39_15_fu_1294_p2 = ($signed(sext_ln39_14_fu_1290_p1) - $signed(window_adjust_2_0_7_load_cast_fu_1262_p1));

assign sub_ln39_1_fu_188_p2 = ($signed(sext_ln39_fu_184_p1) - $signed(window_adjust_2_0_0_load_cast_fu_156_p1));

assign sub_ln39_2_fu_336_p2 = (zext_ln39_6_fu_290_p1 - zext_ln39_5_fu_282_p1);

assign sub_ln39_3_fu_346_p2 = ($signed(sext_ln39_2_fu_342_p1) - $signed(window_adjust_2_0_1_load_cast_fu_314_p1));

assign sub_ln39_4_fu_494_p2 = (zext_ln39_11_fu_448_p1 - zext_ln39_10_fu_440_p1);

assign sub_ln39_5_fu_504_p2 = ($signed(sext_ln39_4_fu_500_p1) - $signed(window_adjust_2_0_2_load_cast_fu_472_p1));

assign sub_ln39_6_fu_652_p2 = (zext_ln39_16_fu_606_p1 - zext_ln39_15_fu_598_p1);

assign sub_ln39_7_fu_662_p2 = ($signed(sext_ln39_6_fu_658_p1) - $signed(window_adjust_2_0_3_load_cast_fu_630_p1));

assign sub_ln39_8_fu_810_p2 = (zext_ln39_21_fu_764_p1 - zext_ln39_20_fu_756_p1);

assign sub_ln39_9_fu_820_p2 = ($signed(sext_ln39_8_fu_816_p1) - $signed(window_adjust_2_0_4_load_cast_fu_788_p1));

assign sub_ln39_fu_178_p2 = (zext_ln39_1_fu_132_p1 - zext_ln39_fu_124_p1);

assign tmp101_fu_1266_p2 = (zext_ln39_38_fu_1254_p1 - zext_ln39_37_fu_1246_p1);

assign tmp83_fu_318_p2 = (zext_ln39_8_fu_306_p1 - zext_ln39_7_fu_298_p1);

assign tmp86_fu_476_p2 = (zext_ln39_13_fu_464_p1 - zext_ln39_12_fu_456_p1);

assign tmp89_fu_634_p2 = (zext_ln39_18_fu_622_p1 - zext_ln39_17_fu_614_p1);

assign tmp92_fu_792_p2 = (zext_ln39_23_fu_780_p1 - zext_ln39_22_fu_772_p1);

assign tmp95_fu_950_p2 = (zext_ln39_28_fu_938_p1 - zext_ln39_27_fu_930_p1);

assign tmp98_fu_1108_p2 = (zext_ln39_33_fu_1096_p1 - zext_ln39_32_fu_1088_p1);

assign tmp_10_fu_234_p4 = {{add_ln39_1_fu_212_p2[12:10]}};

assign tmp_11_fu_384_p3 = sext_ln42_fu_376_p1[32'd31];

assign tmp_12_fu_392_p4 = {{add_ln39_3_fu_370_p2[12:10]}};

assign tmp_13_fu_542_p3 = sext_ln42_9_fu_534_p1[32'd31];

assign tmp_14_fu_550_p4 = {{add_ln39_5_fu_528_p2[12:10]}};

assign tmp_15_fu_700_p3 = sext_ln42_10_fu_692_p1[32'd31];

assign tmp_16_fu_708_p4 = {{add_ln39_7_fu_686_p2[12:10]}};

assign tmp_17_fu_858_p3 = sext_ln42_11_fu_850_p1[32'd31];

assign tmp_18_fu_866_p4 = {{add_ln39_9_fu_844_p2[12:10]}};

assign tmp_19_fu_1016_p3 = sext_ln42_12_fu_1008_p1[32'd31];

assign tmp_1_fu_166_p3 = {{tmp_fu_160_p2}, {1'd0}};

assign tmp_20_fu_1024_p4 = {{add_ln39_11_fu_1002_p2[12:10]}};

assign tmp_21_fu_1174_p3 = sext_ln42_13_fu_1166_p1[32'd31];

assign tmp_22_fu_1182_p4 = {{add_ln39_13_fu_1160_p2[12:10]}};

assign tmp_23_fu_1332_p3 = sext_ln42_14_fu_1324_p1[32'd31];

assign tmp_24_fu_1340_p4 = {{add_ln39_15_fu_1318_p2[12:10]}};

assign tmp_2_fu_324_p3 = {{tmp83_fu_318_p2}, {1'd0}};

assign tmp_3_fu_482_p3 = {{tmp86_fu_476_p2}, {1'd0}};

assign tmp_4_fu_640_p3 = {{tmp89_fu_634_p2}, {1'd0}};

assign tmp_5_fu_798_p3 = {{tmp92_fu_792_p2}, {1'd0}};

assign tmp_6_fu_956_p3 = {{tmp95_fu_950_p2}, {1'd0}};

assign tmp_7_fu_1114_p3 = {{tmp98_fu_1108_p2}, {1'd0}};

assign tmp_8_fu_1272_p3 = {{tmp101_fu_1266_p2}, {1'd0}};

assign tmp_9_fu_226_p3 = sext_ln42_8_fu_218_p1[32'd31];

assign tmp_fu_160_p2 = (zext_ln39_3_fu_148_p1 - zext_ln39_2_fu_140_p1);

assign trunc_ln42_1_fu_380_p1 = add_ln39_3_fu_370_p2[9:0];

assign trunc_ln42_2_fu_538_p1 = add_ln39_5_fu_528_p2[9:0];

assign trunc_ln42_3_fu_696_p1 = add_ln39_7_fu_686_p2[9:0];

assign trunc_ln42_4_fu_854_p1 = add_ln39_9_fu_844_p2[9:0];

assign trunc_ln42_5_fu_1012_p1 = add_ln39_11_fu_1002_p2[9:0];

assign trunc_ln42_6_fu_1170_p1 = add_ln39_13_fu_1160_p2[9:0];

assign trunc_ln42_7_fu_1328_p1 = add_ln39_15_fu_1318_p2[9:0];

assign trunc_ln42_fu_222_p1 = add_ln39_1_fu_212_p2[9:0];

assign window_adjust_2_0_0_load_cast_fu_156_p1 = window_adjust_2_0_0;

assign window_adjust_2_0_1_load_cast_fu_314_p1 = window_adjust_2_0_1;

assign window_adjust_2_0_2_load_cast_fu_472_p1 = window_adjust_2_0_2;

assign window_adjust_2_0_3_load_cast_fu_630_p1 = window_adjust_2_0_3;

assign window_adjust_2_0_4_load_cast_fu_788_p1 = window_adjust_2_0_4;

assign window_adjust_2_0_5_load_cast_fu_946_p1 = window_adjust_2_0_5;

assign window_adjust_2_0_6_load_cast_fu_1104_p1 = window_adjust_2_0_6;

assign window_adjust_2_0_7_load_cast_fu_1262_p1 = window_adjust_2_0_7;

assign xor_ln42_1_fu_408_p2 = (tmp_11_fu_384_p3 ^ 1'd1);

assign xor_ln42_2_fu_566_p2 = (tmp_13_fu_542_p3 ^ 1'd1);

assign xor_ln42_3_fu_724_p2 = (tmp_15_fu_700_p3 ^ 1'd1);

assign xor_ln42_4_fu_882_p2 = (tmp_17_fu_858_p3 ^ 1'd1);

assign xor_ln42_5_fu_1040_p2 = (tmp_19_fu_1016_p3 ^ 1'd1);

assign xor_ln42_6_fu_1198_p2 = (tmp_21_fu_1174_p3 ^ 1'd1);

assign xor_ln42_7_fu_1356_p2 = (tmp_23_fu_1332_p3 ^ 1'd1);

assign xor_ln42_fu_250_p2 = (tmp_9_fu_226_p3 ^ 1'd1);

assign zext_ln39_10_fu_440_p1 = window_adjust_0_0_2;

assign zext_ln39_11_fu_448_p1 = window_adjust_0_2_2;

assign zext_ln39_12_fu_456_p1 = window_adjust_1_0_2;

assign zext_ln39_13_fu_464_p1 = window_adjust_1_2_2;

assign zext_ln39_14_fu_518_p1 = window_adjust_2_2_2;

assign zext_ln39_15_fu_598_p1 = window_adjust_0_0_3;

assign zext_ln39_16_fu_606_p1 = window_adjust_0_2_3;

assign zext_ln39_17_fu_614_p1 = window_adjust_1_0_3;

assign zext_ln39_18_fu_622_p1 = window_adjust_1_2_3;

assign zext_ln39_19_fu_676_p1 = window_adjust_2_2_3;

assign zext_ln39_1_fu_132_p1 = window_adjust_0_2_0;

assign zext_ln39_20_fu_756_p1 = window_adjust_0_0_4;

assign zext_ln39_21_fu_764_p1 = window_adjust_0_2_4;

assign zext_ln39_22_fu_772_p1 = window_adjust_1_0_4;

assign zext_ln39_23_fu_780_p1 = window_adjust_1_2_4;

assign zext_ln39_24_fu_834_p1 = window_adjust_2_2_4;

assign zext_ln39_25_fu_914_p1 = window_adjust_0_0_5;

assign zext_ln39_26_fu_922_p1 = window_adjust_0_2_5;

assign zext_ln39_27_fu_930_p1 = window_adjust_1_0_5;

assign zext_ln39_28_fu_938_p1 = window_adjust_1_2_5;

assign zext_ln39_29_fu_992_p1 = window_adjust_2_2_5;

assign zext_ln39_2_fu_140_p1 = window_adjust_1_0_0;

assign zext_ln39_30_fu_1072_p1 = window_adjust_0_0_6;

assign zext_ln39_31_fu_1080_p1 = window_adjust_0_2_6;

assign zext_ln39_32_fu_1088_p1 = window_adjust_1_0_6;

assign zext_ln39_33_fu_1096_p1 = window_adjust_1_2_6;

assign zext_ln39_34_fu_1150_p1 = window_adjust_2_2_6;

assign zext_ln39_35_fu_1230_p1 = window_adjust_0_0_7;

assign zext_ln39_36_fu_1238_p1 = window_adjust_0_2_7;

assign zext_ln39_37_fu_1246_p1 = window_adjust_1_0_7;

assign zext_ln39_38_fu_1254_p1 = window_adjust_1_2_7;

assign zext_ln39_39_fu_1308_p1 = window_adjust_2_2_7;

assign zext_ln39_3_fu_148_p1 = window_adjust_1_2_0;

assign zext_ln39_4_fu_202_p1 = window_adjust_2_2_0;

assign zext_ln39_5_fu_282_p1 = window_adjust_0_0_1;

assign zext_ln39_6_fu_290_p1 = window_adjust_0_2_1;

assign zext_ln39_7_fu_298_p1 = window_adjust_1_0_1;

assign zext_ln39_8_fu_306_p1 = window_adjust_1_2_1;

assign zext_ln39_9_fu_360_p1 = window_adjust_2_2_1;

assign zext_ln39_fu_124_p1 = window_adjust_0_0_0;

assign ap_return = {{{{{{{{select_ln42_fu_270_p3}, {select_ln42_1_fu_428_p3}}, {select_ln42_2_fu_586_p3}}, {select_ln42_3_fu_744_p3}}, {select_ln42_4_fu_902_p3}}, {select_ln42_5_fu_1060_p3}}, {select_ln42_6_fu_1218_p3}}, {select_ln42_7_fu_1376_p3}};

assign icmp_ln44_1_fu_402_p2 = (($signed(tmp_12_fu_392_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_2_fu_560_p2 = (($signed(tmp_14_fu_550_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_3_fu_718_p2 = (($signed(tmp_16_fu_708_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_4_fu_876_p2 = (($signed(tmp_18_fu_866_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_5_fu_1034_p2 = (($signed(tmp_20_fu_1024_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_6_fu_1192_p2 = (($signed(tmp_22_fu_1182_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_7_fu_1350_p2 = (($signed(tmp_24_fu_1340_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_244_p2 = (($signed(tmp_10_fu_234_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

endmodule //conv2d_3x3_sobelConvolve
