// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_3x3_conv2d_3x3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu1cg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.075000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=0,HLS_SYN_FF=2174,HLS_SYN_LUT=6424,HLS_VERSION=2023_2}" *)

module conv2d_3x3 (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst_n;
input  [79:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output  [79:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;

 reg    ap_rst_n_inv;
reg   [9:0] window_adjust_0_0_0;
reg   [9:0] window_adjust_0_2_0;
reg   [9:0] window_adjust_1_0_0;
reg   [9:0] window_adjust_1_2_0;
reg   [9:0] window_adjust_2_0_0;
reg   [9:0] window_adjust_2_2_0;
reg   [9:0] window_adjust_0_0_1;
reg   [9:0] window_adjust_0_2_1;
reg   [9:0] window_adjust_1_0_1;
reg   [9:0] window_adjust_1_2_1;
reg   [9:0] window_adjust_2_0_1;
reg   [9:0] window_adjust_2_2_1;
reg   [9:0] window_adjust_0_0_2;
reg   [9:0] window_adjust_0_2_2;
reg   [9:0] window_adjust_1_0_2;
reg   [9:0] window_adjust_1_2_2;
reg   [9:0] window_adjust_2_0_2;
reg   [9:0] window_adjust_2_2_2;
reg   [9:0] window_adjust_0_0_3;
reg   [9:0] window_adjust_0_2_3;
reg   [9:0] window_adjust_1_0_3;
reg   [9:0] window_adjust_1_2_3;
reg   [9:0] window_adjust_2_0_3;
reg   [9:0] window_adjust_2_2_3;
reg   [9:0] window_adjust_0_0_4;
reg   [9:0] window_adjust_0_2_4;
reg   [9:0] window_adjust_1_0_4;
reg   [9:0] window_adjust_1_2_4;
reg   [9:0] window_adjust_2_0_4;
reg   [9:0] window_adjust_2_2_4;
reg   [9:0] window_adjust_0_0_5;
reg   [9:0] window_adjust_0_2_5;
reg   [9:0] window_adjust_1_0_5;
reg   [9:0] window_adjust_1_2_5;
reg   [9:0] window_adjust_2_0_5;
reg   [9:0] window_adjust_2_2_5;
reg   [9:0] window_adjust_0_0_6;
reg   [9:0] window_adjust_0_2_6;
reg   [9:0] window_adjust_1_0_6;
reg   [9:0] window_adjust_1_2_6;
reg   [9:0] window_adjust_2_0_6;
reg   [9:0] window_adjust_2_2_6;
reg   [9:0] window_adjust_0_0_7;
reg   [9:0] window_adjust_0_2_7;
reg   [9:0] window_adjust_1_0_7;
reg   [9:0] window_adjust_1_2_7;
reg   [9:0] window_adjust_2_0_7;
reg   [9:0] window_adjust_2_2_7;
reg   [7:0] linebuf_0_0_address0;
reg    linebuf_0_0_ce0;
reg    linebuf_0_0_we0;
wire   [79:0] linebuf_0_0_q0;
reg    linebuf_0_0_ce1;
wire   [79:0] linebuf_0_0_q1;
reg   [7:0] linebuf_1_0_address0;
reg    linebuf_1_0_ce0;
reg    linebuf_1_0_we0;
wire   [79:0] linebuf_1_0_q0;
reg    linebuf_1_0_ce1;
wire   [79:0] linebuf_1_0_q1;
reg   [7:0] linebuf_2_0_address0;
reg    linebuf_2_0_ce0;
reg    linebuf_2_0_we0;
wire   [79:0] linebuf_2_0_q0;
reg    linebuf_2_0_ce1;
wire   [79:0] linebuf_2_0_q1;
reg   [7:0] linebuf_1_1_address0;
reg    linebuf_1_1_ce0;
reg    linebuf_1_1_we0;
wire   [79:0] linebuf_1_1_q0;
reg    linebuf_1_1_ce1;
wire   [79:0] linebuf_1_1_q1;
reg   [7:0] linebuf_2_1_address0;
reg    linebuf_2_1_ce0;
reg    linebuf_2_1_we0;
wire   [79:0] linebuf_2_1_q0;
reg    linebuf_2_1_ce1;
wire   [79:0] linebuf_2_1_q1;
reg   [7:0] linebuf_0_1_address0;
reg    linebuf_0_1_ce0;
reg    linebuf_0_1_we0;
wire   [79:0] linebuf_0_1_q0;
reg    linebuf_0_1_ce1;
wire   [79:0] linebuf_0_1_q1;
reg    output_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state6;
reg   [0:0] cmp_reg_449;
wire    ap_CS_fsm_state7;
wire   [0:0] cmp4_fu_411_p2;
reg   [0:0] cmp4_reg_444;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp_fu_418_p2;
wire   [11:0] row_3_fu_425_p2;
reg   [11:0] row_3_reg_454;
wire   [79:0] grp_shift_register_fu_288_ap_return;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_done;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_idle;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_ready;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TREADY;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_input_r_TREADY;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TDATA;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TVALID;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_0_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_0_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_0_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_0_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_0_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_0_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_0_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_0_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_0_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_0_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_0_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_0_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_1_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_1_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_1_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_1_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_1_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_1_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_1_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_1_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_1_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_1_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_1_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_1_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_2_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_2_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_2_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_2_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_2_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_2_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_2_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_2_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_2_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_2_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_2_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_2_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_3_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_3_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_3_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_3_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_3_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_3_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_3_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_3_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_3_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_3_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_3_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_3_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_4_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_4_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_4_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_4_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_4_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_4_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_4_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_4_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_4_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_4_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_4_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_4_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_5_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_5_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_5_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_5_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_5_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_5_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_5_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_5_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_5_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_5_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_5_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_5_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_6_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_6_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_6_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_6_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_6_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_6_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_6_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_6_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_6_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_6_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_6_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_6_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_7_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_7_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_7_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_7_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_7_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_7_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_7_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_7_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_7_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_7_o_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_7_o;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_7_o_ap_vld;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_address0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_ce0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_we0;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_d0;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_address1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_ce1;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_address0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_ce0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_we0;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_d0;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_address1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_ce1;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_address0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_ce0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_we0;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_d0;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_address1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_ce1;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_address0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_ce0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_we0;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_d0;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_address1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_ce1;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_address0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_ce0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_we0;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_d0;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_address1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_ce1;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_address0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_ce0;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_we0;
wire   [79:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_d0;
wire   [7:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_address1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_ce1;
wire    grp_shift_register_fu_288_ap_start;
wire    grp_shift_register_fu_288_ap_done;
wire    grp_shift_register_fu_288_ap_idle;
wire    grp_shift_register_fu_288_ap_ready;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_0_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_0_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_0_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_1_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_1_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_1_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_2_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_2_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_2_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_3_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_3_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_3_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_4_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_4_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_4_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_5_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_5_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_5_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_6_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_6_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_6_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_0_7_o;
wire    grp_shift_register_fu_288_window_adjust_0_0_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_0_7_o;
wire    grp_shift_register_fu_288_window_adjust_1_0_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_0_7_o;
wire    grp_shift_register_fu_288_window_adjust_2_0_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_0_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_0_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_0_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_1_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_1_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_1_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_2_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_2_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_2_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_3_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_3_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_3_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_4_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_4_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_4_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_5_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_5_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_5_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_6_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_6_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_6_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_0_2_7_o;
wire    grp_shift_register_fu_288_window_adjust_0_2_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_1_2_7_o;
wire    grp_shift_register_fu_288_window_adjust_1_2_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_288_window_adjust_2_2_7_o;
wire    grp_shift_register_fu_288_window_adjust_2_2_7_o_ap_vld;
wire   [7:0] grp_shift_register_fu_288_linebuf_0_0_address0;
wire    grp_shift_register_fu_288_linebuf_0_0_ce0;
wire   [7:0] grp_shift_register_fu_288_linebuf_0_1_address0;
wire    grp_shift_register_fu_288_linebuf_0_1_ce0;
wire   [7:0] grp_shift_register_fu_288_linebuf_1_0_address0;
wire    grp_shift_register_fu_288_linebuf_1_0_ce0;
wire   [7:0] grp_shift_register_fu_288_linebuf_1_1_address0;
wire    grp_shift_register_fu_288_linebuf_1_1_ce0;
wire   [7:0] grp_shift_register_fu_288_linebuf_2_0_address0;
wire    grp_shift_register_fu_288_linebuf_2_0_ce0;
wire   [7:0] grp_shift_register_fu_288_linebuf_2_1_address0;
wire    grp_shift_register_fu_288_linebuf_2_1_ce0;
reg    grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_shift_register_fu_288_ap_start_reg;
reg   [6:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [11:0] row_fu_158;
wire    regslice_both_output_r_U_apdone_blk;
reg    ap_block_state7;
reg    ap_block_state7_io;
wire    ap_CS_fsm_state1;
reg    ap_block_state6;
reg    ap_block_state6_io;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_input_r_U_apdone_blk;
wire   [79:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_U_ack_in;
reg   [79:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 window_adjust_0_0_0 = 10'd0;
#0 window_adjust_0_2_0 = 10'd0;
#0 window_adjust_1_0_0 = 10'd0;
#0 window_adjust_1_2_0 = 10'd0;
#0 window_adjust_2_0_0 = 10'd0;
#0 window_adjust_2_2_0 = 10'd0;
#0 window_adjust_0_0_1 = 10'd0;
#0 window_adjust_0_2_1 = 10'd0;
#0 window_adjust_1_0_1 = 10'd0;
#0 window_adjust_1_2_1 = 10'd0;
#0 window_adjust_2_0_1 = 10'd0;
#0 window_adjust_2_2_1 = 10'd0;
#0 window_adjust_0_0_2 = 10'd0;
#0 window_adjust_0_2_2 = 10'd0;
#0 window_adjust_1_0_2 = 10'd0;
#0 window_adjust_1_2_2 = 10'd0;
#0 window_adjust_2_0_2 = 10'd0;
#0 window_adjust_2_2_2 = 10'd0;
#0 window_adjust_0_0_3 = 10'd0;
#0 window_adjust_0_2_3 = 10'd0;
#0 window_adjust_1_0_3 = 10'd0;
#0 window_adjust_1_2_3 = 10'd0;
#0 window_adjust_2_0_3 = 10'd0;
#0 window_adjust_2_2_3 = 10'd0;
#0 window_adjust_0_0_4 = 10'd0;
#0 window_adjust_0_2_4 = 10'd0;
#0 window_adjust_1_0_4 = 10'd0;
#0 window_adjust_1_2_4 = 10'd0;
#0 window_adjust_2_0_4 = 10'd0;
#0 window_adjust_2_2_4 = 10'd0;
#0 window_adjust_0_0_5 = 10'd0;
#0 window_adjust_0_2_5 = 10'd0;
#0 window_adjust_1_0_5 = 10'd0;
#0 window_adjust_1_2_5 = 10'd0;
#0 window_adjust_2_0_5 = 10'd0;
#0 window_adjust_2_2_5 = 10'd0;
#0 window_adjust_0_0_6 = 10'd0;
#0 window_adjust_0_2_6 = 10'd0;
#0 window_adjust_1_0_6 = 10'd0;
#0 window_adjust_1_2_6 = 10'd0;
#0 window_adjust_2_0_6 = 10'd0;
#0 window_adjust_2_2_6 = 10'd0;
#0 window_adjust_0_0_7 = 10'd0;
#0 window_adjust_0_2_7 = 10'd0;
#0 window_adjust_1_0_7 = 10'd0;
#0 window_adjust_1_2_7 = 10'd0;
#0 window_adjust_2_0_7 = 10'd0;
#0 window_adjust_2_2_7 = 10'd0;
#0 ap_CS_fsm = 7'd1;
#0 grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start_reg = 1'b0;
#0 grp_shift_register_fu_288_ap_start_reg = 1'b0;
#0 row_fu_158 = 12'd0;
end

conv2d_3x3_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 153 ),
    .AddressWidth( 8 ))
linebuf_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_0_0_address0),
    .ce0(linebuf_0_0_ce0),
    .we0(linebuf_0_0_we0),
    .d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_d0),
    .q0(linebuf_0_0_q0),
    .address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_address1),
    .ce1(linebuf_0_0_ce1),
    .q1(linebuf_0_0_q1)
);

conv2d_3x3_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 153 ),
    .AddressWidth( 8 ))
linebuf_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_1_0_address0),
    .ce0(linebuf_1_0_ce0),
    .we0(linebuf_1_0_we0),
    .d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_d0),
    .q0(linebuf_1_0_q0),
    .address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_address1),
    .ce1(linebuf_1_0_ce1),
    .q1(linebuf_1_0_q1)
);

conv2d_3x3_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 153 ),
    .AddressWidth( 8 ))
linebuf_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_2_0_address0),
    .ce0(linebuf_2_0_ce0),
    .we0(linebuf_2_0_we0),
    .d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_d0),
    .q0(linebuf_2_0_q0),
    .address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_address1),
    .ce1(linebuf_2_0_ce1),
    .q1(linebuf_2_0_q1)
);

conv2d_3x3_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 153 ),
    .AddressWidth( 8 ))
linebuf_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_1_1_address0),
    .ce0(linebuf_1_1_ce0),
    .we0(linebuf_1_1_we0),
    .d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_d0),
    .q0(linebuf_1_1_q0),
    .address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_address1),
    .ce1(linebuf_1_1_ce1),
    .q1(linebuf_1_1_q1)
);

conv2d_3x3_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 153 ),
    .AddressWidth( 8 ))
linebuf_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_2_1_address0),
    .ce0(linebuf_2_1_ce0),
    .we0(linebuf_2_1_we0),
    .d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_d0),
    .q0(linebuf_2_1_q0),
    .address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_address1),
    .ce1(linebuf_2_1_ce1),
    .q1(linebuf_2_1_q1)
);

conv2d_3x3_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 153 ),
    .AddressWidth( 8 ))
linebuf_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_0_1_address0),
    .ce0(linebuf_0_1_ce0),
    .we0(linebuf_0_1_we0),
    .d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_d0),
    .q0(linebuf_0_1_q0),
    .address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_address1),
    .ce1(linebuf_0_1_ce1),
    .q1(linebuf_0_1_q1)
);

conv2d_3x3_conv2d_3x3_Pipeline_VITIS_LOOP_136_2 grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start),
    .ap_done(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_done),
    .ap_idle(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_idle),
    .ap_ready(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_ready),
    .input_r_TVALID(input_r_TVALID_int_regslice),
    .output_r_TREADY(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TREADY),
    .input_r_TDATA(input_r_TDATA_int_regslice),
    .input_r_TREADY(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_input_r_TREADY),
    .cmp(cmp_reg_449),
    .row(row_fu_158),
    .cmp4(cmp4_reg_444),
    .output_r_TDATA(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TDATA),
    .output_r_TVALID(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TVALID),
    .window_adjust_0_0_0_i(window_adjust_0_0_0),
    .window_adjust_0_0_0_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_0_o),
    .window_adjust_0_0_0_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_0_o_ap_vld),
    .window_adjust_0_2_0_i(window_adjust_0_2_0),
    .window_adjust_0_2_0_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_0_o),
    .window_adjust_0_2_0_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_0_o_ap_vld),
    .window_adjust_1_0_0_i(window_adjust_1_0_0),
    .window_adjust_1_0_0_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_0_o),
    .window_adjust_1_0_0_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_0_o_ap_vld),
    .window_adjust_1_2_0_i(window_adjust_1_2_0),
    .window_adjust_1_2_0_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_0_o),
    .window_adjust_1_2_0_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_0_o_ap_vld),
    .window_adjust_2_0_0_i(window_adjust_2_0_0),
    .window_adjust_2_0_0_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_0_o),
    .window_adjust_2_0_0_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_0_o_ap_vld),
    .window_adjust_2_2_0_i(window_adjust_2_2_0),
    .window_adjust_2_2_0_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_0_o),
    .window_adjust_2_2_0_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_0_o_ap_vld),
    .window_adjust_0_0_1_i(window_adjust_0_0_1),
    .window_adjust_0_0_1_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_1_o),
    .window_adjust_0_0_1_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_1_o_ap_vld),
    .window_adjust_0_2_1_i(window_adjust_0_2_1),
    .window_adjust_0_2_1_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_1_o),
    .window_adjust_0_2_1_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_1_o_ap_vld),
    .window_adjust_1_0_1_i(window_adjust_1_0_1),
    .window_adjust_1_0_1_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_1_o),
    .window_adjust_1_0_1_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_1_o_ap_vld),
    .window_adjust_1_2_1_i(window_adjust_1_2_1),
    .window_adjust_1_2_1_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_1_o),
    .window_adjust_1_2_1_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_1_o_ap_vld),
    .window_adjust_2_0_1_i(window_adjust_2_0_1),
    .window_adjust_2_0_1_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_1_o),
    .window_adjust_2_0_1_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_1_o_ap_vld),
    .window_adjust_2_2_1_i(window_adjust_2_2_1),
    .window_adjust_2_2_1_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_1_o),
    .window_adjust_2_2_1_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_1_o_ap_vld),
    .window_adjust_0_0_2_i(window_adjust_0_0_2),
    .window_adjust_0_0_2_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_2_o),
    .window_adjust_0_0_2_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_2_o_ap_vld),
    .window_adjust_0_2_2_i(window_adjust_0_2_2),
    .window_adjust_0_2_2_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_2_o),
    .window_adjust_0_2_2_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_2_o_ap_vld),
    .window_adjust_1_0_2_i(window_adjust_1_0_2),
    .window_adjust_1_0_2_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_2_o),
    .window_adjust_1_0_2_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_2_o_ap_vld),
    .window_adjust_1_2_2_i(window_adjust_1_2_2),
    .window_adjust_1_2_2_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_2_o),
    .window_adjust_1_2_2_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_2_o_ap_vld),
    .window_adjust_2_0_2_i(window_adjust_2_0_2),
    .window_adjust_2_0_2_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_2_o),
    .window_adjust_2_0_2_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_2_o_ap_vld),
    .window_adjust_2_2_2_i(window_adjust_2_2_2),
    .window_adjust_2_2_2_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_2_o),
    .window_adjust_2_2_2_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_2_o_ap_vld),
    .window_adjust_0_0_3_i(window_adjust_0_0_3),
    .window_adjust_0_0_3_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_3_o),
    .window_adjust_0_0_3_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_3_o_ap_vld),
    .window_adjust_0_2_3_i(window_adjust_0_2_3),
    .window_adjust_0_2_3_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_3_o),
    .window_adjust_0_2_3_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_3_o_ap_vld),
    .window_adjust_1_0_3_i(window_adjust_1_0_3),
    .window_adjust_1_0_3_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_3_o),
    .window_adjust_1_0_3_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_3_o_ap_vld),
    .window_adjust_1_2_3_i(window_adjust_1_2_3),
    .window_adjust_1_2_3_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_3_o),
    .window_adjust_1_2_3_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_3_o_ap_vld),
    .window_adjust_2_0_3_i(window_adjust_2_0_3),
    .window_adjust_2_0_3_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_3_o),
    .window_adjust_2_0_3_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_3_o_ap_vld),
    .window_adjust_2_2_3_i(window_adjust_2_2_3),
    .window_adjust_2_2_3_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_3_o),
    .window_adjust_2_2_3_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_3_o_ap_vld),
    .window_adjust_0_0_4_i(window_adjust_0_0_4),
    .window_adjust_0_0_4_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_4_o),
    .window_adjust_0_0_4_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_4_o_ap_vld),
    .window_adjust_0_2_4_i(window_adjust_0_2_4),
    .window_adjust_0_2_4_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_4_o),
    .window_adjust_0_2_4_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_4_o_ap_vld),
    .window_adjust_1_0_4_i(window_adjust_1_0_4),
    .window_adjust_1_0_4_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_4_o),
    .window_adjust_1_0_4_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_4_o_ap_vld),
    .window_adjust_1_2_4_i(window_adjust_1_2_4),
    .window_adjust_1_2_4_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_4_o),
    .window_adjust_1_2_4_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_4_o_ap_vld),
    .window_adjust_2_0_4_i(window_adjust_2_0_4),
    .window_adjust_2_0_4_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_4_o),
    .window_adjust_2_0_4_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_4_o_ap_vld),
    .window_adjust_2_2_4_i(window_adjust_2_2_4),
    .window_adjust_2_2_4_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_4_o),
    .window_adjust_2_2_4_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_4_o_ap_vld),
    .window_adjust_0_0_5_i(window_adjust_0_0_5),
    .window_adjust_0_0_5_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_5_o),
    .window_adjust_0_0_5_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_5_o_ap_vld),
    .window_adjust_0_2_5_i(window_adjust_0_2_5),
    .window_adjust_0_2_5_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_5_o),
    .window_adjust_0_2_5_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_5_o_ap_vld),
    .window_adjust_1_0_5_i(window_adjust_1_0_5),
    .window_adjust_1_0_5_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_5_o),
    .window_adjust_1_0_5_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_5_o_ap_vld),
    .window_adjust_1_2_5_i(window_adjust_1_2_5),
    .window_adjust_1_2_5_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_5_o),
    .window_adjust_1_2_5_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_5_o_ap_vld),
    .window_adjust_2_0_5_i(window_adjust_2_0_5),
    .window_adjust_2_0_5_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_5_o),
    .window_adjust_2_0_5_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_5_o_ap_vld),
    .window_adjust_2_2_5_i(window_adjust_2_2_5),
    .window_adjust_2_2_5_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_5_o),
    .window_adjust_2_2_5_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_5_o_ap_vld),
    .window_adjust_0_0_6_i(window_adjust_0_0_6),
    .window_adjust_0_0_6_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_6_o),
    .window_adjust_0_0_6_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_6_o_ap_vld),
    .window_adjust_0_2_6_i(window_adjust_0_2_6),
    .window_adjust_0_2_6_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_6_o),
    .window_adjust_0_2_6_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_6_o_ap_vld),
    .window_adjust_1_0_6_i(window_adjust_1_0_6),
    .window_adjust_1_0_6_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_6_o),
    .window_adjust_1_0_6_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_6_o_ap_vld),
    .window_adjust_1_2_6_i(window_adjust_1_2_6),
    .window_adjust_1_2_6_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_6_o),
    .window_adjust_1_2_6_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_6_o_ap_vld),
    .window_adjust_2_0_6_i(window_adjust_2_0_6),
    .window_adjust_2_0_6_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_6_o),
    .window_adjust_2_0_6_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_6_o_ap_vld),
    .window_adjust_2_2_6_i(window_adjust_2_2_6),
    .window_adjust_2_2_6_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_6_o),
    .window_adjust_2_2_6_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_6_o_ap_vld),
    .window_adjust_0_0_7_i(window_adjust_0_0_7),
    .window_adjust_0_0_7_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_7_o),
    .window_adjust_0_0_7_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_7_o_ap_vld),
    .window_adjust_0_2_7_i(window_adjust_0_2_7),
    .window_adjust_0_2_7_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_7_o),
    .window_adjust_0_2_7_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_7_o_ap_vld),
    .window_adjust_1_0_7_i(window_adjust_1_0_7),
    .window_adjust_1_0_7_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_7_o),
    .window_adjust_1_0_7_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_7_o_ap_vld),
    .window_adjust_1_2_7_i(window_adjust_1_2_7),
    .window_adjust_1_2_7_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_7_o),
    .window_adjust_1_2_7_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_7_o_ap_vld),
    .window_adjust_2_0_7_i(window_adjust_2_0_7),
    .window_adjust_2_0_7_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_7_o),
    .window_adjust_2_0_7_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_7_o_ap_vld),
    .window_adjust_2_2_7_i(window_adjust_2_2_7),
    .window_adjust_2_2_7_o(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_7_o),
    .window_adjust_2_2_7_o_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_7_o_ap_vld),
    .linebuf_0_0_address0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_address0),
    .linebuf_0_0_ce0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_ce0),
    .linebuf_0_0_we0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_we0),
    .linebuf_0_0_d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_d0),
    .linebuf_0_0_q0(linebuf_0_0_q0),
    .linebuf_0_0_address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_address1),
    .linebuf_0_0_ce1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_ce1),
    .linebuf_0_0_q1(linebuf_0_0_q1),
    .linebuf_1_0_address0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_address0),
    .linebuf_1_0_ce0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_ce0),
    .linebuf_1_0_we0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_we0),
    .linebuf_1_0_d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_d0),
    .linebuf_1_0_q0(linebuf_1_0_q0),
    .linebuf_1_0_address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_address1),
    .linebuf_1_0_ce1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_ce1),
    .linebuf_1_0_q1(linebuf_1_0_q1),
    .linebuf_2_0_address0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_address0),
    .linebuf_2_0_ce0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_ce0),
    .linebuf_2_0_we0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_we0),
    .linebuf_2_0_d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_d0),
    .linebuf_2_0_q0(linebuf_2_0_q0),
    .linebuf_2_0_address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_address1),
    .linebuf_2_0_ce1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_ce1),
    .linebuf_2_0_q1(linebuf_2_0_q1),
    .linebuf_1_1_address0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_address0),
    .linebuf_1_1_ce0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_ce0),
    .linebuf_1_1_we0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_we0),
    .linebuf_1_1_d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_d0),
    .linebuf_1_1_q0(linebuf_1_1_q0),
    .linebuf_1_1_address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_address1),
    .linebuf_1_1_ce1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_ce1),
    .linebuf_1_1_q1(linebuf_1_1_q1),
    .linebuf_2_1_address0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_address0),
    .linebuf_2_1_ce0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_ce0),
    .linebuf_2_1_we0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_we0),
    .linebuf_2_1_d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_d0),
    .linebuf_2_1_q0(linebuf_2_1_q0),
    .linebuf_2_1_address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_address1),
    .linebuf_2_1_ce1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_ce1),
    .linebuf_2_1_q1(linebuf_2_1_q1),
    .linebuf_0_1_address0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_address0),
    .linebuf_0_1_ce0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_ce0),
    .linebuf_0_1_we0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_we0),
    .linebuf_0_1_d0(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_d0),
    .linebuf_0_1_q0(linebuf_0_1_q0),
    .linebuf_0_1_address1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_address1),
    .linebuf_0_1_ce1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_ce1),
    .linebuf_0_1_q1(linebuf_0_1_q1)
);

conv2d_3x3_shift_register grp_shift_register_fu_288(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_shift_register_fu_288_ap_start),
    .ap_done(grp_shift_register_fu_288_ap_done),
    .ap_idle(grp_shift_register_fu_288_ap_idle),
    .ap_ready(grp_shift_register_fu_288_ap_ready),
    .row(row_fu_158),
    .window_adjust_0_0_0_i(window_adjust_0_0_0),
    .window_adjust_0_0_0_o(grp_shift_register_fu_288_window_adjust_0_0_0_o),
    .window_adjust_0_0_0_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_0_o_ap_vld),
    .window_adjust_1_0_0_i(window_adjust_1_0_0),
    .window_adjust_1_0_0_o(grp_shift_register_fu_288_window_adjust_1_0_0_o),
    .window_adjust_1_0_0_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_0_o_ap_vld),
    .window_adjust_2_0_0_i(window_adjust_2_0_0),
    .window_adjust_2_0_0_o(grp_shift_register_fu_288_window_adjust_2_0_0_o),
    .window_adjust_2_0_0_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_0_o_ap_vld),
    .window_adjust_0_0_1_i(window_adjust_0_0_1),
    .window_adjust_0_0_1_o(grp_shift_register_fu_288_window_adjust_0_0_1_o),
    .window_adjust_0_0_1_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_1_o_ap_vld),
    .window_adjust_1_0_1_i(window_adjust_1_0_1),
    .window_adjust_1_0_1_o(grp_shift_register_fu_288_window_adjust_1_0_1_o),
    .window_adjust_1_0_1_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_1_o_ap_vld),
    .window_adjust_2_0_1_i(window_adjust_2_0_1),
    .window_adjust_2_0_1_o(grp_shift_register_fu_288_window_adjust_2_0_1_o),
    .window_adjust_2_0_1_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_1_o_ap_vld),
    .window_adjust_0_0_2_i(window_adjust_0_0_2),
    .window_adjust_0_0_2_o(grp_shift_register_fu_288_window_adjust_0_0_2_o),
    .window_adjust_0_0_2_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_2_o_ap_vld),
    .window_adjust_1_0_2_i(window_adjust_1_0_2),
    .window_adjust_1_0_2_o(grp_shift_register_fu_288_window_adjust_1_0_2_o),
    .window_adjust_1_0_2_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_2_o_ap_vld),
    .window_adjust_2_0_2_i(window_adjust_2_0_2),
    .window_adjust_2_0_2_o(grp_shift_register_fu_288_window_adjust_2_0_2_o),
    .window_adjust_2_0_2_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_2_o_ap_vld),
    .window_adjust_0_0_3_i(window_adjust_0_0_3),
    .window_adjust_0_0_3_o(grp_shift_register_fu_288_window_adjust_0_0_3_o),
    .window_adjust_0_0_3_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_3_o_ap_vld),
    .window_adjust_1_0_3_i(window_adjust_1_0_3),
    .window_adjust_1_0_3_o(grp_shift_register_fu_288_window_adjust_1_0_3_o),
    .window_adjust_1_0_3_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_3_o_ap_vld),
    .window_adjust_2_0_3_i(window_adjust_2_0_3),
    .window_adjust_2_0_3_o(grp_shift_register_fu_288_window_adjust_2_0_3_o),
    .window_adjust_2_0_3_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_3_o_ap_vld),
    .window_adjust_0_0_4_i(window_adjust_0_0_4),
    .window_adjust_0_0_4_o(grp_shift_register_fu_288_window_adjust_0_0_4_o),
    .window_adjust_0_0_4_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_4_o_ap_vld),
    .window_adjust_1_0_4_i(window_adjust_1_0_4),
    .window_adjust_1_0_4_o(grp_shift_register_fu_288_window_adjust_1_0_4_o),
    .window_adjust_1_0_4_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_4_o_ap_vld),
    .window_adjust_2_0_4_i(window_adjust_2_0_4),
    .window_adjust_2_0_4_o(grp_shift_register_fu_288_window_adjust_2_0_4_o),
    .window_adjust_2_0_4_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_4_o_ap_vld),
    .window_adjust_0_0_5_i(window_adjust_0_0_5),
    .window_adjust_0_0_5_o(grp_shift_register_fu_288_window_adjust_0_0_5_o),
    .window_adjust_0_0_5_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_5_o_ap_vld),
    .window_adjust_1_0_5_i(window_adjust_1_0_5),
    .window_adjust_1_0_5_o(grp_shift_register_fu_288_window_adjust_1_0_5_o),
    .window_adjust_1_0_5_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_5_o_ap_vld),
    .window_adjust_2_0_5_i(window_adjust_2_0_5),
    .window_adjust_2_0_5_o(grp_shift_register_fu_288_window_adjust_2_0_5_o),
    .window_adjust_2_0_5_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_5_o_ap_vld),
    .window_adjust_0_0_6_i(window_adjust_0_0_6),
    .window_adjust_0_0_6_o(grp_shift_register_fu_288_window_adjust_0_0_6_o),
    .window_adjust_0_0_6_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_6_o_ap_vld),
    .window_adjust_1_0_6_i(window_adjust_1_0_6),
    .window_adjust_1_0_6_o(grp_shift_register_fu_288_window_adjust_1_0_6_o),
    .window_adjust_1_0_6_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_6_o_ap_vld),
    .window_adjust_2_0_6_i(window_adjust_2_0_6),
    .window_adjust_2_0_6_o(grp_shift_register_fu_288_window_adjust_2_0_6_o),
    .window_adjust_2_0_6_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_6_o_ap_vld),
    .window_adjust_0_0_7_i(window_adjust_0_0_7),
    .window_adjust_0_0_7_o(grp_shift_register_fu_288_window_adjust_0_0_7_o),
    .window_adjust_0_0_7_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_0_7_o_ap_vld),
    .window_adjust_1_0_7_i(window_adjust_1_0_7),
    .window_adjust_1_0_7_o(grp_shift_register_fu_288_window_adjust_1_0_7_o),
    .window_adjust_1_0_7_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_0_7_o_ap_vld),
    .window_adjust_2_0_7_i(window_adjust_2_0_7),
    .window_adjust_2_0_7_o(grp_shift_register_fu_288_window_adjust_2_0_7_o),
    .window_adjust_2_0_7_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_0_7_o_ap_vld),
    .window_adjust_0_2_0_i(window_adjust_0_2_0),
    .window_adjust_0_2_0_o(grp_shift_register_fu_288_window_adjust_0_2_0_o),
    .window_adjust_0_2_0_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_0_o_ap_vld),
    .window_adjust_1_2_0_i(window_adjust_1_2_0),
    .window_adjust_1_2_0_o(grp_shift_register_fu_288_window_adjust_1_2_0_o),
    .window_adjust_1_2_0_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_0_o_ap_vld),
    .window_adjust_2_2_0_i(window_adjust_2_2_0),
    .window_adjust_2_2_0_o(grp_shift_register_fu_288_window_adjust_2_2_0_o),
    .window_adjust_2_2_0_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_0_o_ap_vld),
    .window_adjust_0_2_1_i(window_adjust_0_2_1),
    .window_adjust_0_2_1_o(grp_shift_register_fu_288_window_adjust_0_2_1_o),
    .window_adjust_0_2_1_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_1_o_ap_vld),
    .window_adjust_1_2_1_i(window_adjust_1_2_1),
    .window_adjust_1_2_1_o(grp_shift_register_fu_288_window_adjust_1_2_1_o),
    .window_adjust_1_2_1_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_1_o_ap_vld),
    .window_adjust_2_2_1_i(window_adjust_2_2_1),
    .window_adjust_2_2_1_o(grp_shift_register_fu_288_window_adjust_2_2_1_o),
    .window_adjust_2_2_1_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_1_o_ap_vld),
    .window_adjust_0_2_2_i(window_adjust_0_2_2),
    .window_adjust_0_2_2_o(grp_shift_register_fu_288_window_adjust_0_2_2_o),
    .window_adjust_0_2_2_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_2_o_ap_vld),
    .window_adjust_1_2_2_i(window_adjust_1_2_2),
    .window_adjust_1_2_2_o(grp_shift_register_fu_288_window_adjust_1_2_2_o),
    .window_adjust_1_2_2_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_2_o_ap_vld),
    .window_adjust_2_2_2_i(window_adjust_2_2_2),
    .window_adjust_2_2_2_o(grp_shift_register_fu_288_window_adjust_2_2_2_o),
    .window_adjust_2_2_2_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_2_o_ap_vld),
    .window_adjust_0_2_3_i(window_adjust_0_2_3),
    .window_adjust_0_2_3_o(grp_shift_register_fu_288_window_adjust_0_2_3_o),
    .window_adjust_0_2_3_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_3_o_ap_vld),
    .window_adjust_1_2_3_i(window_adjust_1_2_3),
    .window_adjust_1_2_3_o(grp_shift_register_fu_288_window_adjust_1_2_3_o),
    .window_adjust_1_2_3_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_3_o_ap_vld),
    .window_adjust_2_2_3_i(window_adjust_2_2_3),
    .window_adjust_2_2_3_o(grp_shift_register_fu_288_window_adjust_2_2_3_o),
    .window_adjust_2_2_3_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_3_o_ap_vld),
    .window_adjust_0_2_4_i(window_adjust_0_2_4),
    .window_adjust_0_2_4_o(grp_shift_register_fu_288_window_adjust_0_2_4_o),
    .window_adjust_0_2_4_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_4_o_ap_vld),
    .window_adjust_1_2_4_i(window_adjust_1_2_4),
    .window_adjust_1_2_4_o(grp_shift_register_fu_288_window_adjust_1_2_4_o),
    .window_adjust_1_2_4_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_4_o_ap_vld),
    .window_adjust_2_2_4_i(window_adjust_2_2_4),
    .window_adjust_2_2_4_o(grp_shift_register_fu_288_window_adjust_2_2_4_o),
    .window_adjust_2_2_4_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_4_o_ap_vld),
    .window_adjust_0_2_5_i(window_adjust_0_2_5),
    .window_adjust_0_2_5_o(grp_shift_register_fu_288_window_adjust_0_2_5_o),
    .window_adjust_0_2_5_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_5_o_ap_vld),
    .window_adjust_1_2_5_i(window_adjust_1_2_5),
    .window_adjust_1_2_5_o(grp_shift_register_fu_288_window_adjust_1_2_5_o),
    .window_adjust_1_2_5_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_5_o_ap_vld),
    .window_adjust_2_2_5_i(window_adjust_2_2_5),
    .window_adjust_2_2_5_o(grp_shift_register_fu_288_window_adjust_2_2_5_o),
    .window_adjust_2_2_5_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_5_o_ap_vld),
    .window_adjust_0_2_6_i(window_adjust_0_2_6),
    .window_adjust_0_2_6_o(grp_shift_register_fu_288_window_adjust_0_2_6_o),
    .window_adjust_0_2_6_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_6_o_ap_vld),
    .window_adjust_1_2_6_i(window_adjust_1_2_6),
    .window_adjust_1_2_6_o(grp_shift_register_fu_288_window_adjust_1_2_6_o),
    .window_adjust_1_2_6_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_6_o_ap_vld),
    .window_adjust_2_2_6_i(window_adjust_2_2_6),
    .window_adjust_2_2_6_o(grp_shift_register_fu_288_window_adjust_2_2_6_o),
    .window_adjust_2_2_6_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_6_o_ap_vld),
    .window_adjust_0_2_7_i(window_adjust_0_2_7),
    .window_adjust_0_2_7_o(grp_shift_register_fu_288_window_adjust_0_2_7_o),
    .window_adjust_0_2_7_o_ap_vld(grp_shift_register_fu_288_window_adjust_0_2_7_o_ap_vld),
    .window_adjust_1_2_7_i(window_adjust_1_2_7),
    .window_adjust_1_2_7_o(grp_shift_register_fu_288_window_adjust_1_2_7_o),
    .window_adjust_1_2_7_o_ap_vld(grp_shift_register_fu_288_window_adjust_1_2_7_o_ap_vld),
    .window_adjust_2_2_7_i(window_adjust_2_2_7),
    .window_adjust_2_2_7_o(grp_shift_register_fu_288_window_adjust_2_2_7_o),
    .window_adjust_2_2_7_o_ap_vld(grp_shift_register_fu_288_window_adjust_2_2_7_o_ap_vld),
    .linebuf_0_0_address0(grp_shift_register_fu_288_linebuf_0_0_address0),
    .linebuf_0_0_ce0(grp_shift_register_fu_288_linebuf_0_0_ce0),
    .linebuf_0_0_q0(linebuf_0_0_q0),
    .linebuf_0_1_address0(grp_shift_register_fu_288_linebuf_0_1_address0),
    .linebuf_0_1_ce0(grp_shift_register_fu_288_linebuf_0_1_ce0),
    .linebuf_0_1_q0(linebuf_0_1_q0),
    .linebuf_1_0_address0(grp_shift_register_fu_288_linebuf_1_0_address0),
    .linebuf_1_0_ce0(grp_shift_register_fu_288_linebuf_1_0_ce0),
    .linebuf_1_0_q0(linebuf_1_0_q0),
    .linebuf_1_1_address0(grp_shift_register_fu_288_linebuf_1_1_address0),
    .linebuf_1_1_ce0(grp_shift_register_fu_288_linebuf_1_1_ce0),
    .linebuf_1_1_q0(linebuf_1_1_q0),
    .linebuf_2_0_address0(grp_shift_register_fu_288_linebuf_2_0_address0),
    .linebuf_2_0_ce0(grp_shift_register_fu_288_linebuf_2_0_ce0),
    .linebuf_2_0_q0(linebuf_2_0_q0),
    .linebuf_2_1_address0(grp_shift_register_fu_288_linebuf_2_1_address0),
    .linebuf_2_1_ce0(grp_shift_register_fu_288_linebuf_2_1_ce0),
    .linebuf_2_1_q0(linebuf_2_1_q0),
    .ap_return(grp_shift_register_fu_288_ap_return)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 80 ))
regslice_both_input_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 80 ))
regslice_both_output_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_ready == 1'b1)) begin
            grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_shift_register_fu_288_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_shift_register_fu_288_ap_start_reg <= 1'b1;
        end else if ((grp_shift_register_fu_288_ap_ready == 1'b1)) begin
            grp_shift_register_fu_288_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        row_fu_158 <= 12'd0;
    end else if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7)) & (1'b1 == ap_CS_fsm_state7))) begin
        row_fu_158 <= row_3_reg_454;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_0 <= grp_shift_register_fu_288_window_adjust_0_0_0_o;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_0_o_ap_vld == 1'b1))) begin
        window_adjust_0_0_0 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_1 <= grp_shift_register_fu_288_window_adjust_0_0_1_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_2 <= grp_shift_register_fu_288_window_adjust_0_0_2_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_3 <= grp_shift_register_fu_288_window_adjust_0_0_3_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_3 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_4 <= grp_shift_register_fu_288_window_adjust_0_0_4_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_4 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_5 <= grp_shift_register_fu_288_window_adjust_0_0_5_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_5 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_6 <= grp_shift_register_fu_288_window_adjust_0_0_6_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_6 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_7 <= grp_shift_register_fu_288_window_adjust_0_0_7_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_7 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_0_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_0 <= grp_shift_register_fu_288_window_adjust_0_2_0_o;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_0_o_ap_vld == 1'b1))) begin
        window_adjust_0_2_0 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_1 <= grp_shift_register_fu_288_window_adjust_0_2_1_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_2 <= grp_shift_register_fu_288_window_adjust_0_2_2_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_3 <= grp_shift_register_fu_288_window_adjust_0_2_3_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_3 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_4 <= grp_shift_register_fu_288_window_adjust_0_2_4_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_4 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_5 <= grp_shift_register_fu_288_window_adjust_0_2_5_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_5 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_6 <= grp_shift_register_fu_288_window_adjust_0_2_6_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_6 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_0_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_7 <= grp_shift_register_fu_288_window_adjust_0_2_7_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_7 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_0_2_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_0 <= grp_shift_register_fu_288_window_adjust_1_0_0_o;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_0_o_ap_vld == 1'b1))) begin
        window_adjust_1_0_0 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_1 <= grp_shift_register_fu_288_window_adjust_1_0_1_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_2 <= grp_shift_register_fu_288_window_adjust_1_0_2_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_3 <= grp_shift_register_fu_288_window_adjust_1_0_3_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_3 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_4 <= grp_shift_register_fu_288_window_adjust_1_0_4_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_4 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_5 <= grp_shift_register_fu_288_window_adjust_1_0_5_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_5 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_6 <= grp_shift_register_fu_288_window_adjust_1_0_6_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_6 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_7 <= grp_shift_register_fu_288_window_adjust_1_0_7_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_7 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_0_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_0 <= grp_shift_register_fu_288_window_adjust_1_2_0_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_0 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_1 <= grp_shift_register_fu_288_window_adjust_1_2_1_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_2 <= grp_shift_register_fu_288_window_adjust_1_2_2_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_3 <= grp_shift_register_fu_288_window_adjust_1_2_3_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_3 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_4 <= grp_shift_register_fu_288_window_adjust_1_2_4_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_4 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_5 <= grp_shift_register_fu_288_window_adjust_1_2_5_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_5 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_6 <= grp_shift_register_fu_288_window_adjust_1_2_6_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_6 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_1_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_7 <= grp_shift_register_fu_288_window_adjust_1_2_7_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_7 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_1_2_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_0 <= grp_shift_register_fu_288_window_adjust_2_0_0_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_0 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_1 <= grp_shift_register_fu_288_window_adjust_2_0_1_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_2 <= grp_shift_register_fu_288_window_adjust_2_0_2_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_3 <= grp_shift_register_fu_288_window_adjust_2_0_3_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_3 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_4 <= grp_shift_register_fu_288_window_adjust_2_0_4_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_4 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_5 <= grp_shift_register_fu_288_window_adjust_2_0_5_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_5 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_6 <= grp_shift_register_fu_288_window_adjust_2_0_6_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_6 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_7 <= grp_shift_register_fu_288_window_adjust_2_0_7_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_7 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_0_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_0 <= grp_shift_register_fu_288_window_adjust_2_2_0_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_0 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_1 <= grp_shift_register_fu_288_window_adjust_2_2_1_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_2 <= grp_shift_register_fu_288_window_adjust_2_2_2_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_3 <= grp_shift_register_fu_288_window_adjust_2_2_3_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_3 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_4 <= grp_shift_register_fu_288_window_adjust_2_2_4_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_4 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_5 <= grp_shift_register_fu_288_window_adjust_2_2_5_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_5 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_6 <= grp_shift_register_fu_288_window_adjust_2_2_6_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_6 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_288_window_adjust_2_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_7 <= grp_shift_register_fu_288_window_adjust_2_2_7_o;
    end else if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_7 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_window_adjust_2_2_7_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp4_reg_444 <= cmp4_fu_411_p2;
        cmp_reg_449 <= cmp_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_3_reg_454 <= row_3_fu_425_p2;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_TREADY_int_regslice = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_input_r_TREADY;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_0_address0 = grp_shift_register_fu_288_linebuf_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_address0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_address0;
    end else begin
        linebuf_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_0_ce0 = grp_shift_register_fu_288_linebuf_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_ce0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_ce0;
    end else begin
        linebuf_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_ce1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_ce1;
    end else begin
        linebuf_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_we0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_0_we0;
    end else begin
        linebuf_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_1_address0 = grp_shift_register_fu_288_linebuf_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_address0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_address0;
    end else begin
        linebuf_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_1_ce0 = grp_shift_register_fu_288_linebuf_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_ce0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_ce0;
    end else begin
        linebuf_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_ce1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_ce1;
    end else begin
        linebuf_0_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_we0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_0_1_we0;
    end else begin
        linebuf_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_0_address0 = grp_shift_register_fu_288_linebuf_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_address0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_address0;
    end else begin
        linebuf_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_0_ce0 = grp_shift_register_fu_288_linebuf_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_ce0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_ce0;
    end else begin
        linebuf_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_ce1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_ce1;
    end else begin
        linebuf_1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_we0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_0_we0;
    end else begin
        linebuf_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_1_address0 = grp_shift_register_fu_288_linebuf_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_address0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_address0;
    end else begin
        linebuf_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_1_ce0 = grp_shift_register_fu_288_linebuf_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_ce0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_ce0;
    end else begin
        linebuf_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_ce1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_ce1;
    end else begin
        linebuf_1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_we0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_1_1_we0;
    end else begin
        linebuf_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_0_address0 = grp_shift_register_fu_288_linebuf_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_address0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_address0;
    end else begin
        linebuf_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_0_ce0 = grp_shift_register_fu_288_linebuf_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_ce0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_ce0;
    end else begin
        linebuf_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_ce1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_ce1;
    end else begin
        linebuf_2_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_we0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_0_we0;
    end else begin
        linebuf_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_1_address0 = grp_shift_register_fu_288_linebuf_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_address0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_address0;
    end else begin
        linebuf_2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_1_ce0 = grp_shift_register_fu_288_linebuf_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_ce0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_ce0;
    end else begin
        linebuf_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_ce1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_ce1;
    end else begin
        linebuf_2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_we0 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_linebuf_2_1_we0;
    end else begin
        linebuf_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state7) & (cmp_reg_449 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (cmp_reg_449 == 1'd1)))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp_reg_449 == 1'd1))) begin
        output_r_TDATA_int_regslice = grp_shift_register_fu_288_ap_return;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TVALID == 1'b1))) begin
        output_r_TDATA_int_regslice = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TDATA;
    end else begin
        output_r_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6)) & (1'b1 == ap_CS_fsm_state6) & (cmp_reg_449 == 1'd1))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_r_TVALID_int_regslice = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TVALID;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7)) & (1'b1 == ap_CS_fsm_state7) & (cmp4_reg_444 == 1'd1) & (cmp_reg_449 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7)) & (1'b1 == ap_CS_fsm_state7) & (cmp4_reg_444 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_block_state6 = ((output_r_TREADY_int_regslice == 1'b0) & (cmp_reg_449 == 1'd1));
end

always @ (*) begin
    ap_block_state6_io = ((output_r_TREADY_int_regslice == 1'b0) & (cmp_reg_449 == 1'd1));
end

always @ (*) begin
    ap_block_state7 = ((regslice_both_output_r_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (cmp_reg_449 == 1'd1)));
end

always @ (*) begin
    ap_block_state7_io = ((output_r_TREADY_int_regslice == 1'b0) & (cmp_reg_449 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp4_fu_411_p2 = ((row_fu_158 == 12'd2048) ? 1'b1 : 1'b0);

assign cmp_fu_418_p2 = ((row_fu_158 != 12'd0) ? 1'b1 : 1'b0);

assign grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start = grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_ap_start_reg;

assign grp_conv2d_3x3_Pipeline_VITIS_LOOP_136_2_fu_169_output_r_TREADY = (output_r_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_shift_register_fu_288_ap_start = grp_shift_register_fu_288_ap_start_reg;

assign input_r_TREADY = regslice_both_input_r_U_ack_in;

assign output_r_TVALID = regslice_both_output_r_U_vld_out;

assign row_3_fu_425_p2 = (row_fu_158 + 12'd1);

endmodule //conv2d_3x3
