// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_conv2d_3x3_Pipeline_VITIS_LOOP_157_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_dout,
        output_r_empty_n,
        output_r_read,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        arr2
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [79:0] output_r_dout;
input   output_r_empty_n;
output   output_r_read;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [63:0] m_axi_gmem_WDATA;
output  [7:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [63:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] arr2;

reg ap_idle;
reg output_r_read;
reg m_axi_gmem_AWVALID;
reg[63:0] m_axi_gmem_AWADDR;
reg m_axi_gmem_WVALID;
reg[63:0] m_axi_gmem_WDATA;
reg m_axi_gmem_BREADY;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
reg   [0:0] icmp_ln157_reg_649;
reg    ap_block_state5_pp0_stage4_iter0;
reg   [0:0] icmp_ln167_2_reg_693;
reg    ap_predicate_op102_write_state5;
reg   [0:0] icmp_ln167_3_reg_713;
reg    ap_predicate_op105_writereq_state5;
reg    ap_block_state5_io;
reg   [0:0] icmp_ln157_reg_649_pp0_iter1_reg;
reg   [0:0] icmp_ln167_2_reg_693_pp0_iter1_reg;
reg    ap_predicate_op140_writeresp_state10;
reg    ap_block_state10_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_subdone;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] output_addr;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage4;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_B;
reg   [0:0] icmp_ln167_3_reg_713_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] icmp_ln167_1_reg_673;
reg   [0:0] icmp_ln167_1_reg_673_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln167_reg_653;
reg   [0:0] icmp_ln167_reg_653_pp0_iter1_reg;
reg   [0:0] icmp_ln167_4_reg_733;
reg   [0:0] icmp_ln167_4_reg_733_pp0_iter1_reg;
reg    output_r_blk_n;
reg    ap_predicate_op121_write_state6;
reg    ap_block_state6_io;
reg    ap_predicate_op143_writeresp_state11;
reg    ap_block_state11_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_predicate_op56_write_state3;
reg    ap_predicate_op59_writereq_state3;
reg    ap_block_state3_io;
reg    ap_predicate_op131_writeresp_state8;
reg    ap_block_state8_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
reg   [79:0] reg_234;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_predicate_op41_writereq_state2;
reg    ap_block_state2_io;
reg    ap_block_state7_io;
reg    ap_block_state12_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_predicate_op77_write_state4;
reg    ap_predicate_op80_writereq_state4;
reg    ap_block_state4_io;
reg    ap_predicate_op136_writeresp_state9;
reg    ap_block_state9_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
reg   [79:0] reg_244;
reg    ap_block_pp0_stage4_11001;
wire   [0:0] icmp_ln157_fu_256_p2;
wire   [0:0] icmp_ln167_fu_262_p2;
wire   [31:0] add_ln169_fu_268_p2;
reg   [60:0] trunc_ln4_reg_662;
wire   [0:0] icmp_ln167_1_fu_329_p2;
wire   [31:0] add_ln169_2_fu_335_p2;
reg   [60:0] trunc_ln169_1_reg_682;
wire   [0:0] icmp_ln167_2_fu_389_p2;
wire   [31:0] add_ln169_4_fu_395_p2;
reg   [60:0] trunc_ln169_2_reg_702;
wire   [0:0] icmp_ln167_3_fu_467_p2;
wire   [31:0] add_ln169_6_fu_473_p2;
reg   [60:0] trunc_ln169_3_reg_722;
wire   [0:0] icmp_ln167_4_fu_545_p2;
reg   [60:0] trunc_ln169_4_reg_737;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [31:0] ap_phi_reg_pp0_iter0_empty_31_reg_188;
reg   [31:0] ap_phi_reg_pp0_iter0_empty_30_reg_197;
reg   [31:0] ap_phi_reg_pp0_iter0_empty_29_reg_206;
reg   [31:0] ap_phi_reg_pp0_iter0_empty_reg_215;
wire  signed [63:0] sext_ln169_1_fu_319_p1;
wire  signed [63:0] sext_ln169_3_fu_379_p1;
wire  signed [63:0] sext_ln169_5_fu_457_p1;
wire  signed [63:0] sext_ln169_7_fu_535_p1;
wire  signed [63:0] sext_ln169_9_fu_613_p1;
wire   [63:0] trunc_ln169_fu_374_p1;
reg    ap_block_pp0_stage2_01001;
wire   [63:0] tmp_76_fu_448_p3;
reg    ap_block_pp0_stage3_01001;
wire   [63:0] tmp_77_fu_526_p3;
reg    ap_block_pp0_stage4_01001;
wire   [63:0] tmp_78_fu_604_p3;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
wire   [31:0] add_ln169_8_fu_551_p2;
reg   [19:0] i_fu_92;
wire   [19:0] i_2_fu_308_p2;
wire    ap_loop_init;
reg   [19:0] ap_sig_allocacmp_i_1;
wire   [34:0] shl_ln_fu_280_p3;
wire  signed [63:0] sext_ln169_fu_288_p1;
wire   [63:0] add_ln169_1_fu_292_p2;
wire   [34:0] shl_ln169_1_fu_347_p3;
wire  signed [63:0] sext_ln169_2_fu_355_p1;
wire   [63:0] add_ln169_3_fu_359_p2;
wire   [34:0] shl_ln169_2_fu_407_p3;
wire  signed [63:0] sext_ln169_4_fu_415_p1;
wire   [63:0] add_ln169_5_fu_419_p2;
wire   [47:0] trunc_ln169_5_fu_444_p1;
wire   [15:0] tmp_17_fu_434_p4;
wire   [34:0] shl_ln169_3_fu_485_p3;
wire  signed [63:0] sext_ln169_6_fu_493_p1;
wire   [63:0] add_ln169_7_fu_497_p2;
wire   [31:0] trunc_ln169_6_fu_522_p1;
wire   [31:0] tmp_19_fu_512_p4;
wire   [34:0] shl_ln169_4_fu_563_p3;
wire  signed [63:0] sext_ln169_8_fu_571_p1;
wire   [63:0] add_ln169_9_fu_575_p2;
wire   [15:0] trunc_ln169_7_fu_600_p1;
wire   [47:0] tmp_21_fu_590_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage1;
reg    ap_idle_pp0_0to0;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_596;
reg    ap_condition_595;
reg    ap_condition_593;
reg    ap_condition_598;
reg    ap_condition_842;
reg    ap_condition_846;
reg    ap_condition_850;
reg    ap_condition_854;
reg    ap_condition_858;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 output_addr = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_92 = 20'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_3x3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_596)) begin
        if ((icmp_ln167_2_fu_389_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_empty_29_reg_206 <= add_ln169_4_fu_395_p2;
        end else if ((icmp_ln167_2_fu_389_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_empty_29_reg_206 <= output_addr;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_595)) begin
        if ((icmp_ln167_1_fu_329_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_empty_30_reg_197 <= add_ln169_2_fu_335_p2;
        end else if ((icmp_ln167_1_fu_329_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_empty_30_reg_197 <= output_addr;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_593)) begin
        if ((icmp_ln167_fu_262_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_empty_31_reg_188 <= output_addr;
        end else if ((icmp_ln167_fu_262_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_empty_31_reg_188 <= add_ln169_fu_268_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_598)) begin
        if ((icmp_ln167_3_fu_467_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_empty_reg_215 <= add_ln169_6_fu_473_p2;
        end else if ((icmp_ln167_3_fu_467_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_empty_reg_215 <= output_addr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln157_fu_256_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_92 <= i_2_fu_308_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_92 <= 20'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_858)) begin
            output_addr <= add_ln169_fu_268_p2;
        end else if ((1'b1 == ap_condition_854)) begin
            output_addr <= add_ln169_2_fu_335_p2;
        end else if ((1'b1 == ap_condition_850)) begin
            output_addr <= add_ln169_4_fu_395_p2;
        end else if ((1'b1 == ap_condition_846)) begin
            output_addr <= add_ln169_6_fu_473_p2;
        end else if ((1'b1 == ap_condition_842)) begin
            output_addr <= add_ln169_8_fu_551_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln157_reg_649 <= icmp_ln157_fu_256_p2;
        icmp_ln157_reg_649_pp0_iter1_reg <= icmp_ln157_reg_649;
        icmp_ln167_reg_653 <= icmp_ln167_fu_262_p2;
        icmp_ln167_reg_653_pp0_iter1_reg <= icmp_ln167_reg_653;
        trunc_ln4_reg_662 <= {{add_ln169_1_fu_292_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        icmp_ln167_1_reg_673 <= icmp_ln167_1_fu_329_p2;
        icmp_ln167_1_reg_673_pp0_iter1_reg <= icmp_ln167_1_reg_673;
        trunc_ln169_1_reg_682 <= {{add_ln169_3_fu_359_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        icmp_ln167_2_reg_693 <= icmp_ln167_2_fu_389_p2;
        icmp_ln167_2_reg_693_pp0_iter1_reg <= icmp_ln167_2_reg_693;
        trunc_ln169_2_reg_702 <= {{add_ln169_5_fu_419_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        icmp_ln167_3_reg_713 <= icmp_ln167_3_fu_467_p2;
        icmp_ln167_3_reg_713_pp0_iter1_reg <= icmp_ln167_3_reg_713;
        trunc_ln169_3_reg_722 <= {{add_ln169_7_fu_497_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        icmp_ln167_4_reg_733 <= icmp_ln167_4_fu_545_p2;
        icmp_ln167_4_reg_733_pp0_iter1_reg <= icmp_ln167_4_reg_733;
        trunc_ln169_4_reg_737 <= {{add_ln169_9_fu_575_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        reg_234 <= output_r_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        reg_244 <= output_r_dout;
    end
end

always @ (*) begin
    if (((icmp_ln157_reg_649 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd0))) begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 20'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_92;
    end
end

always @ (*) begin
    if ((((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln167_reg_653 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln167_1_reg_673 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (icmp_ln167_2_reg_693 == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_4_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4) & (ap_predicate_op105_writereq_state5 == 1'b1)))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln167_4_reg_733_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln167_3_reg_713_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4) & (ap_predicate_op140_writeresp_state10 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_reg_653_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_1_reg_673_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1)))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln167_3_reg_713 == 1'd1)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln167_reg_653 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln167_1_reg_673 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_4_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4) & (ap_predicate_op102_write_state5 == 1'b1)))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_4_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_AWADDR = sext_ln169_9_fu_613_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op105_writereq_state5 == 1'b1))) begin
        m_axi_gmem_AWADDR = sext_ln169_7_fu_535_p1;
    end else if (((ap_predicate_op80_writereq_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_AWADDR = sext_ln169_5_fu_457_p1;
    end else if (((ap_predicate_op59_writereq_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        m_axi_gmem_AWADDR = sext_ln169_3_fu_379_p1;
    end else if (((ap_predicate_op41_writereq_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_AWADDR = sext_ln169_1_fu_319_p1;
    end else begin
        m_axi_gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op80_writereq_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_predicate_op41_writereq_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_predicate_op59_writereq_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_4_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op105_writereq_state5 == 1'b1)))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op136_writeresp_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_predicate_op131_writeresp_state8 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op143_writeresp_state11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln167_4_reg_733_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op140_writeresp_state10 == 1'b1)))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_4_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        m_axi_gmem_WDATA = {{reg_244[79:16]}};
    end else if (((ap_predicate_op121_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        m_axi_gmem_WDATA = tmp_78_fu_604_p3;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op102_write_state5 == 1'b1))) begin
        m_axi_gmem_WDATA = tmp_77_fu_526_p3;
    end else if (((ap_predicate_op77_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        m_axi_gmem_WDATA = tmp_76_fu_448_p3;
    end else if (((ap_predicate_op56_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        m_axi_gmem_WDATA = trunc_ln169_fu_374_p1;
    end else begin
        m_axi_gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op77_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_predicate_op56_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_predicate_op121_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln167_4_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op102_write_state5 == 1'b1)))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)))) begin
        output_r_blk_n = output_r_empty_n;
    end else begin
        output_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        output_r_read = 1'b1;
    end else begin
        output_r_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln169_1_fu_292_p2 = ($signed(sext_ln169_fu_288_p1) + $signed(arr2));

assign add_ln169_2_fu_335_p2 = (ap_phi_reg_pp0_iter0_empty_31_reg_188 + 32'd1);

assign add_ln169_3_fu_359_p2 = ($signed(sext_ln169_2_fu_355_p1) + $signed(arr2));

assign add_ln169_4_fu_395_p2 = (ap_phi_reg_pp0_iter0_empty_30_reg_197 + 32'd1);

assign add_ln169_5_fu_419_p2 = ($signed(sext_ln169_4_fu_415_p1) + $signed(arr2));

assign add_ln169_6_fu_473_p2 = (ap_phi_reg_pp0_iter0_empty_29_reg_206 + 32'd1);

assign add_ln169_7_fu_497_p2 = ($signed(sext_ln169_6_fu_493_p1) + $signed(arr2));

assign add_ln169_8_fu_551_p2 = (ap_phi_reg_pp0_iter0_empty_reg_215 + 32'd1);

assign add_ln169_9_fu_575_p2 = ($signed(sext_ln169_8_fu_571_p1) + $signed(arr2));

assign add_ln169_fu_268_p2 = (output_addr + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage1_iter2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage1_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage1_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0))));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage2_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage2_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage2_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage2_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage2_iter0))));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage3_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage3_iter0))));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage4_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage4_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage4_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage4_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage4_iter0))));
end

always @ (*) begin
    ap_block_state10_pp0_stage4_iter1 = ((m_axi_gmem_BVALID == 1'b0) & (ap_predicate_op140_writeresp_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter2 = ((m_axi_gmem_BVALID == 1'b0) & (ap_predicate_op143_writeresp_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state12_pp0_stage1_iter2 = ((m_axi_gmem_BVALID == 1'b0) & (icmp_ln167_4_reg_733_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem_AWREADY == 1'b0) & (ap_predicate_op41_writereq_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln157_reg_649 == 1'd1) & (output_r_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = (((m_axi_gmem_AWREADY == 1'b0) & (ap_predicate_op59_writereq_state3 == 1'b1)) | ((m_axi_gmem_WREADY == 1'b0) & (ap_predicate_op56_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((icmp_ln157_reg_649 == 1'd1) & (output_r_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = (((m_axi_gmem_AWREADY == 1'b0) & (ap_predicate_op80_writereq_state4 == 1'b1)) | ((m_axi_gmem_WREADY == 1'b0) & (ap_predicate_op77_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((icmp_ln157_reg_649 == 1'd1) & (output_r_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_io = (((m_axi_gmem_AWREADY == 1'b0) & (ap_predicate_op105_writereq_state5 == 1'b1)) | ((m_axi_gmem_WREADY == 1'b0) & (ap_predicate_op102_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((icmp_ln157_reg_649 == 1'd1) & (output_r_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = (((m_axi_gmem_AWREADY == 1'b0) & (icmp_ln167_4_reg_733 == 1'd1)) | ((m_axi_gmem_WREADY == 1'b0) & (ap_predicate_op121_write_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_state7_io = ((m_axi_gmem_WREADY == 1'b0) & (icmp_ln167_4_reg_733 == 1'd1));
end

always @ (*) begin
    ap_block_state8_pp0_stage2_iter1 = ((m_axi_gmem_BVALID == 1'b0) & (ap_predicate_op131_writeresp_state8 == 1'b1));
end

always @ (*) begin
    ap_block_state9_pp0_stage3_iter1 = ((m_axi_gmem_BVALID == 1'b0) & (ap_predicate_op136_writeresp_state9 == 1'b1));
end

always @ (*) begin
    ap_condition_593 = ((icmp_ln157_fu_256_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_595 = ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001));
end

always @ (*) begin
    ap_condition_596 = ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001));
end

always @ (*) begin
    ap_condition_598 = ((icmp_ln157_reg_649 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001));
end

always @ (*) begin
    ap_condition_842 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_4_fu_545_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001));
end

always @ (*) begin
    ap_condition_846 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_3_fu_467_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001));
end

always @ (*) begin
    ap_condition_850 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_2_fu_389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001));
end

always @ (*) begin
    ap_condition_854 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_1_fu_329_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001));
end

always @ (*) begin
    ap_condition_858 = ((icmp_ln167_fu_262_p2 == 1'd1) & (icmp_ln157_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

always @ (*) begin
    ap_predicate_op102_write_state5 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_2_reg_693 == 1'd1));
end

always @ (*) begin
    ap_predicate_op105_writereq_state5 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_3_reg_713 == 1'd1));
end

always @ (*) begin
    ap_predicate_op121_write_state6 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_3_reg_713 == 1'd1));
end

always @ (*) begin
    ap_predicate_op131_writeresp_state8 = ((icmp_ln167_reg_653_pp0_iter1_reg == 1'd1) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op136_writeresp_state9 = ((icmp_ln167_1_reg_673_pp0_iter1_reg == 1'd1) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op140_writeresp_state10 = ((icmp_ln167_2_reg_693_pp0_iter1_reg == 1'd1) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op143_writeresp_state11 = ((icmp_ln167_3_reg_713_pp0_iter1_reg == 1'd1) & (icmp_ln157_reg_649_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op41_writereq_state2 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_reg_653 == 1'd1));
end

always @ (*) begin
    ap_predicate_op56_write_state3 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_reg_653 == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_writereq_state3 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_1_reg_673 == 1'd1));
end

always @ (*) begin
    ap_predicate_op77_write_state4 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_1_reg_673 == 1'd1));
end

always @ (*) begin
    ap_predicate_op80_writereq_state4 = ((icmp_ln157_reg_649 == 1'd1) & (icmp_ln167_2_reg_693 == 1'd1));
end

assign i_2_fu_308_p2 = (ap_sig_allocacmp_i_1 + 20'd4);

assign icmp_ln157_fu_256_p2 = ((ap_sig_allocacmp_i_1 < 20'd626688) ? 1'b1 : 1'b0);

assign icmp_ln167_1_fu_329_p2 = (($signed(ap_phi_reg_pp0_iter0_empty_31_reg_188) < $signed(32'd783360)) ? 1'b1 : 1'b0);

assign icmp_ln167_2_fu_389_p2 = (($signed(ap_phi_reg_pp0_iter0_empty_30_reg_197) < $signed(32'd783360)) ? 1'b1 : 1'b0);

assign icmp_ln167_3_fu_467_p2 = (($signed(ap_phi_reg_pp0_iter0_empty_29_reg_206) < $signed(32'd783360)) ? 1'b1 : 1'b0);

assign icmp_ln167_4_fu_545_p2 = (($signed(ap_phi_reg_pp0_iter0_empty_reg_215) < $signed(32'd783360)) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_262_p2 = (($signed(output_addr) < $signed(32'd783360)) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 8'd255;

assign m_axi_gmem_WUSER = 1'd0;

assign sext_ln169_1_fu_319_p1 = $signed(trunc_ln4_reg_662);

assign sext_ln169_2_fu_355_p1 = $signed(shl_ln169_1_fu_347_p3);

assign sext_ln169_3_fu_379_p1 = $signed(trunc_ln169_1_reg_682);

assign sext_ln169_4_fu_415_p1 = $signed(shl_ln169_2_fu_407_p3);

assign sext_ln169_5_fu_457_p1 = $signed(trunc_ln169_2_reg_702);

assign sext_ln169_6_fu_493_p1 = $signed(shl_ln169_3_fu_485_p3);

assign sext_ln169_7_fu_535_p1 = $signed(trunc_ln169_3_reg_722);

assign sext_ln169_8_fu_571_p1 = $signed(shl_ln169_4_fu_563_p3);

assign sext_ln169_9_fu_613_p1 = $signed(trunc_ln169_4_reg_737);

assign sext_ln169_fu_288_p1 = $signed(shl_ln_fu_280_p3);

assign shl_ln169_1_fu_347_p3 = {{ap_phi_reg_pp0_iter0_empty_31_reg_188}, {3'd0}};

assign shl_ln169_2_fu_407_p3 = {{ap_phi_reg_pp0_iter0_empty_30_reg_197}, {3'd0}};

assign shl_ln169_3_fu_485_p3 = {{ap_phi_reg_pp0_iter0_empty_29_reg_206}, {3'd0}};

assign shl_ln169_4_fu_563_p3 = {{ap_phi_reg_pp0_iter0_empty_reg_215}, {3'd0}};

assign shl_ln_fu_280_p3 = {{output_addr}, {3'd0}};

assign tmp_17_fu_434_p4 = {{reg_234[79:64]}};

assign tmp_19_fu_512_p4 = {{reg_244[79:48]}};

assign tmp_21_fu_590_p4 = {{reg_234[79:32]}};

assign tmp_76_fu_448_p3 = {{trunc_ln169_5_fu_444_p1}, {tmp_17_fu_434_p4}};

assign tmp_77_fu_526_p3 = {{trunc_ln169_6_fu_522_p1}, {tmp_19_fu_512_p4}};

assign tmp_78_fu_604_p3 = {{trunc_ln169_7_fu_600_p1}, {tmp_21_fu_590_p4}};

assign trunc_ln169_5_fu_444_p1 = reg_244[47:0];

assign trunc_ln169_6_fu_522_p1 = reg_234[31:0];

assign trunc_ln169_7_fu_600_p1 = reg_244[15:0];

assign trunc_ln169_fu_374_p1 = reg_234[63:0];

endmodule //conv2d_3x3_conv2d_3x3_Pipeline_VITIS_LOOP_157_1
