// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_3x3_conv2d_3x3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu1cg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.489750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=379,HLS_SYN_LUT=1149,HLS_VERSION=2023_2}" *)

module conv2d_3x3 (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [15:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output  [15:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;

 reg    ap_rst_n_inv;
reg   [9:0] window_0_2;
reg   [9:0] window_0_1;
reg   [9:0] window_1_2;
reg   [9:0] window_1_1;
reg   [9:0] window_2_2;
reg   [9:0] window_2_1;
reg    output_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
reg   [11:0] row_2_reg_644;
wire    ap_CS_fsm_state3;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_done;
reg    ap_predicate_pred37_state4;
wire    ap_CS_fsm_state5;
reg   [0:0] icmp_reg_676;
reg    ap_predicate_op103_write_state4;
reg    ap_block_state4;
reg    ap_block_state4_io;
reg    ap_predicate_pred37_state5;
reg    ap_predicate_pred57_state4;
reg    ap_predicate_pred57_state5;
reg    ap_predicate_pred67_state5;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp64_fu_272_p2;
reg   [0:0] cmp64_reg_666;
wire   [0:0] cmp_fu_279_p2;
reg   [0:0] cmp_reg_671;
wire   [0:0] icmp_fu_296_p2;
wire   [11:0] row_3_fu_303_p2;
reg   [11:0] row_3_reg_681;
wire   [15:0] zext_ln181_fu_374_p1;
wire   [15:0] zext_ln166_fu_427_p1;
wire   [15:0] zext_ln195_fu_526_p1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_idle;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_ready;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TREADY;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_input_r_TREADY;
wire   [15:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TDATA;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TVALID;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_loc_2_out;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_loc_2_out_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_loc_2_out;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_loc_2_out_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_loc_2_out;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_loc_2_out_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_ap_vld;
wire   [9:0] grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2;
wire    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_ap_vld;
reg    grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start_reg;
wire    ap_CS_fsm_state1;
reg   [11:0] row_fu_88;
reg    ap_predicate_op108_write_state5;
wire    regslice_both_output_r_U_apdone_blk;
reg    ap_block_state5;
reg    ap_block_state5_io;
reg   [9:0] window_2_1_loc_0_fu_92;
reg   [9:0] window_2_2_loc_0_fu_96;
reg   [9:0] window_1_1_loc_0_fu_100;
reg   [9:0] window_1_2_loc_0_fu_104;
reg   [9:0] window_0_1_loc_0_fu_108;
reg   [9:0] window_0_2_loc_0_fu_112;
wire   [10:0] tmp_fu_286_p4;
wire   [10:0] zext_ln67_7_fu_330_p1;
wire   [10:0] zext_ln67_6_fu_326_p1;
wire   [10:0] sum_10_fu_334_p2;
wire   [0:0] tmp_12_fu_340_p3;
wire   [0:0] xor_ln70_1_fu_348_p2;
wire   [9:0] select_ln70_4_fu_354_p3;
wire   [9:0] trunc_ln70_1_fu_362_p1;
wire   [9:0] select_ln70_1_fu_366_p3;
wire   [10:0] zext_ln67_fu_379_p1;
wire   [10:0] zext_ln67_5_fu_383_p1;
wire   [10:0] sum_fu_387_p2;
wire   [0:0] tmp_11_fu_393_p3;
wire   [0:0] xor_ln70_fu_401_p2;
wire   [9:0] select_ln70_3_fu_407_p3;
wire   [9:0] trunc_ln70_fu_415_p1;
wire   [9:0] select_ln70_fu_419_p3;
wire   [10:0] zext_ln67_10_fu_440_p1;
wire   [10:0] zext_ln67_8_fu_432_p1;
wire   [10:0] sub_ln67_fu_448_p2;
wire  signed [11:0] sext_ln67_3_fu_454_p1;
wire   [11:0] zext_ln67_11_fu_444_p1;
wire   [11:0] sum_11_fu_458_p2;
wire   [11:0] zext_ln67_9_fu_436_p1;
wire   [11:0] sum_12_fu_464_p2;
wire   [1:0] tmp_14_fu_478_p4;
wire   [0:0] tmp_13_fu_470_p3;
wire   [0:0] xor_ln70_2_fu_494_p2;
wire   [0:0] icmp_ln72_fu_488_p2;
wire   [0:0] or_ln70_fu_508_p2;
wire   [9:0] select_ln70_5_fu_500_p3;
wire   [9:0] trunc_ln70_2_fu_514_p1;
wire   [9:0] select_ln70_2_fu_518_p3;
reg    ap_predicate_pred67_state4;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_input_r_U_apdone_blk;
wire   [15:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_U_ack_in;
reg   [15:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 window_0_2 = 10'd0;
#0 window_0_1 = 10'd0;
#0 window_1_2 = 10'd0;
#0 window_1_1 = 10'd0;
#0 window_2_2 = 10'd0;
#0 window_2_1 = 10'd0;
#0 ap_CS_fsm = 5'd1;
#0 grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start_reg = 1'b0;
#0 row_fu_88 = 12'd0;
#0 window_2_1_loc_0_fu_92 = 10'd0;
#0 window_2_2_loc_0_fu_96 = 10'd0;
#0 window_1_1_loc_0_fu_100 = 10'd0;
#0 window_1_2_loc_0_fu_104 = 10'd0;
#0 window_0_1_loc_0_fu_108 = 10'd0;
#0 window_0_2_loc_0_fu_112 = 10'd0;
end

conv2d_3x3_conv2d_3x3_Pipeline_VITIS_LOOP_88_2 grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start),
    .ap_done(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_done),
    .ap_idle(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_idle),
    .ap_ready(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_ready),
    .input_r_TVALID(input_r_TVALID_int_regslice),
    .output_r_TREADY(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TREADY),
    .window_0_2_loc_0(window_0_2_loc_0_fu_112),
    .window_0_1_loc_0(window_0_1_loc_0_fu_108),
    .window_1_2_loc_0(window_1_2_loc_0_fu_104),
    .window_1_1_loc_0(window_1_1_loc_0_fu_100),
    .window_2_2_loc_0(window_2_2_loc_0_fu_96),
    .window_2_1_loc_0(window_2_1_loc_0_fu_92),
    .input_r_TDATA(input_r_TDATA_int_regslice),
    .input_r_TREADY(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_input_r_TREADY),
    .output_r_TDATA(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TDATA),
    .output_r_TVALID(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TVALID),
    .cmp(cmp_reg_671),
    .icmp(icmp_reg_676),
    .cmp64(cmp64_reg_666),
    .window_0_2_loc_2_out(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_loc_2_out),
    .window_0_2_loc_2_out_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_loc_2_out_ap_vld),
    .window_0_1_loc_2_out(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out),
    .window_0_1_loc_2_out_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out_ap_vld),
    .window_1_2_loc_2_out(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_loc_2_out),
    .window_1_2_loc_2_out_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_loc_2_out_ap_vld),
    .window_1_1_loc_2_out(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out),
    .window_1_1_loc_2_out_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out_ap_vld),
    .window_2_2_loc_2_out(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_loc_2_out),
    .window_2_2_loc_2_out_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_loc_2_out_ap_vld),
    .window_2_1_loc_2_out(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out),
    .window_2_1_loc_2_out_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out_ap_vld),
    .window_0_1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1),
    .window_0_1_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_ap_vld),
    .window_1_1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1),
    .window_1_1_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_ap_vld),
    .window_2_1(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1),
    .window_2_1_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_ap_vld),
    .window_0_2(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2),
    .window_0_2_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_ap_vld),
    .window_1_2(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2),
    .window_1_2_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_ap_vld),
    .window_2_2(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2),
    .window_2_2_ap_vld(grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_ap_vld)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_ready == 1'b1)) begin
            grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        row_fu_88 <= 12'd0;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        row_fu_88 <= row_3_reg_681;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        window_0_1_loc_0_fu_108 <= window_0_1;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        window_0_1_loc_0_fu_108 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        window_0_2_loc_0_fu_112 <= window_0_2;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        window_0_2_loc_0_fu_112 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_loc_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        window_1_1_loc_0_fu_100 <= window_1_1;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        window_1_1_loc_0_fu_100 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        window_1_2_loc_0_fu_104 <= window_1_2;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        window_1_2_loc_0_fu_104 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_loc_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        window_2_1_loc_0_fu_92 <= window_2_1;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        window_2_1_loc_0_fu_92 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        window_2_2_loc_0_fu_96 <= window_2_2;
    end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        window_2_2_loc_0_fu_96 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_loc_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_predicate_pred37_state4 <= (row_2_reg_644 == 12'd1);
        ap_predicate_pred57_state4 <= (row_2_reg_644 == 12'd2048);
        ap_predicate_pred67_state4 <= (~(row_2_reg_644 == 12'd2048) & ~(row_2_reg_644 == 12'd1) & (icmp_reg_676 == 1'd1));
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_predicate_pred37_state5 <= (row_2_reg_644 == 12'd1);
        ap_predicate_pred57_state5 <= (row_2_reg_644 == 12'd2048);
        ap_predicate_pred67_state5 <= (~(row_2_reg_644 == 12'd2048) & ~(row_2_reg_644 == 12'd1) & (icmp_reg_676 == 1'd1));
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp64_reg_666 <= cmp64_fu_272_p2;
        cmp_reg_671 <= cmp_fu_279_p2;
        icmp_reg_676 <= icmp_fu_296_p2;
        row_2_reg_644 <= row_fu_88;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_3_reg_681 <= row_3_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_ap_vld == 1'b1))) begin
        window_0_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2_ap_vld == 1'b1))) begin
        window_0_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_ap_vld == 1'b1))) begin
        window_1_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2_ap_vld == 1'b1))) begin
        window_1_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_ap_vld == 1'b1))) begin
        window_2_1 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2_ap_vld == 1'b1))) begin
        window_2_2 <= grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_2;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_TREADY_int_regslice = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_input_r_TREADY;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred67_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred57_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred57_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_predicate_pred37_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_op103_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_predicate_pred37_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op103_write_state4 == 1'b1) & (1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        output_r_TDATA_int_regslice = zext_ln195_fu_526_p1;
    end else if (((ap_predicate_pred37_state4 == 1'b1) & (1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        output_r_TDATA_int_regslice = zext_ln166_fu_427_p1;
    end else if (((ap_predicate_pred57_state4 == 1'b1) & (1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        output_r_TDATA_int_regslice = zext_ln181_fu_374_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TVALID == 1'b1))) begin
        output_r_TDATA_int_regslice = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TDATA;
    end else begin
        output_r_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (ap_predicate_pred57_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (ap_predicate_op103_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (ap_predicate_pred37_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_r_TVALID_int_regslice = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TVALID;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (ap_predicate_pred57_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5) & (cmp64_reg_666 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state4 = (((ap_predicate_op103_write_state4 == 1'b1) & (output_r_TREADY_int_regslice == 1'b0)) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd2048)) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd1)));
end

always @ (*) begin
    ap_block_state4_io = (((ap_predicate_op103_write_state4 == 1'b1) & (output_r_TREADY_int_regslice == 1'b0)) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd2048)) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd1)));
end

always @ (*) begin
    ap_block_state5 = ((regslice_both_output_r_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd2048)) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd1)) | ((output_r_TREADY_int_regslice == 1'b0) & (ap_predicate_op108_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_io = (((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd2048)) | ((output_r_TREADY_int_regslice == 1'b0) & (row_2_reg_644 == 12'd1)) | ((output_r_TREADY_int_regslice == 1'b0) & (ap_predicate_op108_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op103_write_state4 = (~(row_2_reg_644 == 12'd2048) & ~(row_2_reg_644 == 12'd1) & (icmp_reg_676 == 1'd1));
end

always @ (*) begin
    ap_predicate_op108_write_state5 = (~(row_2_reg_644 == 12'd2048) & ~(row_2_reg_644 == 12'd1) & (icmp_reg_676 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp64_fu_272_p2 = ((row_fu_88 == 12'd2048) ? 1'b1 : 1'b0);

assign cmp_fu_279_p2 = ((row_fu_88 == 12'd1) ? 1'b1 : 1'b0);

assign grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_ap_start_reg;

assign grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_output_r_TREADY = (output_r_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_fu_296_p2 = ((tmp_fu_286_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_488_p2 = ((tmp_14_fu_478_p4 == 2'd1) ? 1'b1 : 1'b0);

assign input_r_TREADY = regslice_both_input_r_U_ack_in;

assign or_ln70_fu_508_p2 = (tmp_13_fu_470_p3 | icmp_ln72_fu_488_p2);

assign output_r_TVALID = regslice_both_output_r_U_vld_out;

assign row_3_fu_303_p2 = (row_fu_88 + 12'd1);

assign select_ln70_1_fu_366_p3 = ((tmp_12_fu_340_p3[0:0] == 1'b1) ? select_ln70_4_fu_354_p3 : trunc_ln70_1_fu_362_p1);

assign select_ln70_2_fu_518_p3 = ((or_ln70_fu_508_p2[0:0] == 1'b1) ? select_ln70_5_fu_500_p3 : trunc_ln70_2_fu_514_p1);

assign select_ln70_3_fu_407_p3 = ((xor_ln70_fu_401_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln70_4_fu_354_p3 = ((xor_ln70_1_fu_348_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln70_5_fu_500_p3 = ((xor_ln70_2_fu_494_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln70_fu_419_p3 = ((tmp_11_fu_393_p3[0:0] == 1'b1) ? select_ln70_3_fu_407_p3 : trunc_ln70_fu_415_p1);

assign sext_ln67_3_fu_454_p1 = $signed(sub_ln67_fu_448_p2);

assign sub_ln67_fu_448_p2 = (zext_ln67_10_fu_440_p1 - zext_ln67_8_fu_432_p1);

assign sum_10_fu_334_p2 = (zext_ln67_7_fu_330_p1 - zext_ln67_6_fu_326_p1);

assign sum_11_fu_458_p2 = ($signed(sext_ln67_3_fu_454_p1) - $signed(zext_ln67_11_fu_444_p1));

assign sum_12_fu_464_p2 = (sum_11_fu_458_p2 + zext_ln67_9_fu_436_p1);

assign sum_fu_387_p2 = (zext_ln67_fu_379_p1 - zext_ln67_5_fu_383_p1);

assign tmp_11_fu_393_p3 = sum_fu_387_p2[32'd10];

assign tmp_12_fu_340_p3 = sum_10_fu_334_p2[32'd10];

assign tmp_13_fu_470_p3 = sum_12_fu_464_p2[32'd11];

assign tmp_14_fu_478_p4 = {{sum_12_fu_464_p2[11:10]}};

assign tmp_fu_286_p4 = {{row_fu_88[11:1]}};

assign trunc_ln70_1_fu_362_p1 = sum_10_fu_334_p2[9:0];

assign trunc_ln70_2_fu_514_p1 = sum_12_fu_464_p2[9:0];

assign trunc_ln70_fu_415_p1 = sum_fu_387_p2[9:0];

assign xor_ln70_1_fu_348_p2 = (tmp_12_fu_340_p3 ^ 1'd1);

assign xor_ln70_2_fu_494_p2 = (tmp_13_fu_470_p3 ^ 1'd1);

assign xor_ln70_fu_401_p2 = (tmp_11_fu_393_p3 ^ 1'd1);

assign zext_ln166_fu_427_p1 = select_ln70_fu_419_p3;

assign zext_ln181_fu_374_p1 = select_ln70_1_fu_366_p3;

assign zext_ln195_fu_526_p1 = select_ln70_2_fu_518_p3;

assign zext_ln67_10_fu_440_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out;

assign zext_ln67_11_fu_444_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out;

assign zext_ln67_5_fu_383_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_2_1_loc_2_out;

assign zext_ln67_6_fu_326_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out;

assign zext_ln67_7_fu_330_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out;

assign zext_ln67_8_fu_432_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_0_1_loc_2_out;

assign zext_ln67_9_fu_436_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out;

assign zext_ln67_fu_379_p1 = grp_conv2d_3x3_Pipeline_VITIS_LOOP_88_2_fu_147_window_1_1_loc_2_out;

endmodule //conv2d_3x3
